from __future__ import annotations

# Generated by scripts/build_pokemon_names.py. Do not edit by hand.
POKEMON_NAME_ALIASES = {
  "abomasnow": {
    "dex_id": 460,
    "english": "Abomasnow",
    "japanese": "ユキノオー"
  },
  "abra": {
    "dex_id": 63,
    "english": "Abra",
    "japanese": "ケーシィ"
  },
  "absol": {
    "dex_id": 359,
    "english": "Absol",
    "japanese": "アブソル"
  },
  "accelgor": {
    "dex_id": 617,
    "english": "Accelgor",
    "japanese": "アギルダー"
  },
  "aegislash": {
    "dex_id": 681,
    "english": "Aegislash",
    "japanese": "ギルガルド"
  },
  "aerodactyl": {
    "dex_id": 142,
    "english": "Aerodactyl",
    "japanese": "プテラ"
  },
  "aggron": {
    "dex_id": 306,
    "english": "Aggron",
    "japanese": "ボスゴドラ"
  },
  "aipom": {
    "dex_id": 190,
    "english": "Aipom",
    "japanese": "エイパム"
  },
  "alakazam": {
    "dex_id": 65,
    "english": "Alakazam",
    "japanese": "フーディン"
  },
  "alcremie": {
    "dex_id": 869,
    "english": "Alcremie",
    "japanese": "マホイップ"
  },
  "alomomola": {
    "dex_id": 594,
    "english": "Alomomola",
    "japanese": "ママンボウ"
  },
  "altaria": {
    "dex_id": 334,
    "english": "Altaria",
    "japanese": "チルタリス"
  },
  "amaura": {
    "dex_id": 698,
    "english": "Amaura",
    "japanese": "アマルス"
  },
  "ambipom": {
    "dex_id": 424,
    "english": "Ambipom",
    "japanese": "エテボース"
  },
  "amoonguss": {
    "dex_id": 591,
    "english": "Amoonguss",
    "japanese": "モロバレル"
  },
  "ampharos": {
    "dex_id": 181,
    "english": "Ampharos",
    "japanese": "デンリュウ"
  },
  "annihilape": {
    "dex_id": 979,
    "english": "Annihilape",
    "japanese": "コノヨザル"
  },
  "anorith": {
    "dex_id": 347,
    "english": "Anorith",
    "japanese": "アノプス"
  },
  "appletun": {
    "dex_id": 842,
    "english": "Appletun",
    "japanese": "タルップル"
  },
  "applin": {
    "dex_id": 840,
    "english": "Applin",
    "japanese": "カジッチュ"
  },
  "araquanid": {
    "dex_id": 752,
    "english": "Araquanid",
    "japanese": "オニシズクモ"
  },
  "arbok": {
    "dex_id": 24,
    "english": "Arbok",
    "japanese": "アーボック"
  },
  "arboliva": {
    "dex_id": 930,
    "english": "Arboliva",
    "japanese": "オリーヴァ"
  },
  "arcanine": {
    "dex_id": 59,
    "english": "Arcanine",
    "japanese": "ウインディ"
  },
  "arceus": {
    "dex_id": 493,
    "english": "Arceus",
    "japanese": "アルセウス"
  },
  "archaludon": {
    "dex_id": 1018,
    "english": "Archaludon",
    "japanese": "ブリジュラス"
  },
  "archen": {
    "dex_id": 566,
    "english": "Archen",
    "japanese": "アーケン"
  },
  "archeops": {
    "dex_id": 567,
    "english": "Archeops",
    "japanese": "アーケオス"
  },
  "arctibax": {
    "dex_id": 997,
    "english": "Arctibax",
    "japanese": "セゴール"
  },
  "arctovish": {
    "dex_id": 883,
    "english": "Arctovish",
    "japanese": "ウオチルドン"
  },
  "arctozolt": {
    "dex_id": 881,
    "english": "Arctozolt",
    "japanese": "パッチルドン"
  },
  "ariados": {
    "dex_id": 168,
    "english": "Ariados",
    "japanese": "アリアドス"
  },
  "armaldo": {
    "dex_id": 348,
    "english": "Armaldo",
    "japanese": "アーマルド"
  },
  "armarouge": {
    "dex_id": 936,
    "english": "Armarouge",
    "japanese": "グレンアルマ"
  },
  "aromatisse": {
    "dex_id": 683,
    "english": "Aromatisse",
    "japanese": "フレフワン"
  },
  "aron": {
    "dex_id": 304,
    "english": "Aron",
    "japanese": "ココドラ"
  },
  "arrokuda": {
    "dex_id": 846,
    "english": "Arrokuda",
    "japanese": "サシカマス"
  },
  "articuno": {
    "dex_id": 144,
    "english": "Articuno",
    "japanese": "フリーザー"
  },
  "audino": {
    "dex_id": 531,
    "english": "Audino",
    "japanese": "タブンネ"
  },
  "aurorus": {
    "dex_id": 699,
    "english": "Aurorus",
    "japanese": "アマルルガ"
  },
  "avalugg": {
    "dex_id": 713,
    "english": "Avalugg",
    "japanese": "クレベース"
  },
  "axew": {
    "dex_id": 610,
    "english": "Axew",
    "japanese": "キバゴ"
  },
  "azelf": {
    "dex_id": 482,
    "english": "Azelf",
    "japanese": "アグノム"
  },
  "azumarill": {
    "dex_id": 184,
    "english": "Azumarill",
    "japanese": "マリルリ"
  },
  "azurill": {
    "dex_id": 298,
    "english": "Azurill",
    "japanese": "ルリリ"
  },
  "bagon": {
    "dex_id": 371,
    "english": "Bagon",
    "japanese": "タツベイ"
  },
  "baltoy": {
    "dex_id": 343,
    "english": "Baltoy",
    "japanese": "ヤジロン"
  },
  "banette": {
    "dex_id": 354,
    "english": "Banette",
    "japanese": "ジュペッタ"
  },
  "barbaracle": {
    "dex_id": 689,
    "english": "Barbaracle",
    "japanese": "ガメノデス"
  },
  "barboach": {
    "dex_id": 339,
    "english": "Barboach",
    "japanese": "ドジョッチ"
  },
  "barraskewda": {
    "dex_id": 847,
    "english": "Barraskewda",
    "japanese": "カマスジョー"
  },
  "basculegion": {
    "dex_id": 902,
    "english": "Basculegion",
    "japanese": "イダイトウ"
  },
  "basculin": {
    "dex_id": 550,
    "english": "Basculin",
    "japanese": "バスラオ"
  },
  "bastiodon": {
    "dex_id": 411,
    "english": "Bastiodon",
    "japanese": "トリデプス"
  },
  "baxcalibur": {
    "dex_id": 998,
    "english": "Baxcalibur",
    "japanese": "セグレイブ"
  },
  "bayleef": {
    "dex_id": 153,
    "english": "Bayleef",
    "japanese": "ベイリーフ"
  },
  "beartic": {
    "dex_id": 614,
    "english": "Beartic",
    "japanese": "ツンベアー"
  },
  "beautifly": {
    "dex_id": 267,
    "english": "Beautifly",
    "japanese": "アゲハント"
  },
  "beedrill": {
    "dex_id": 15,
    "english": "Beedrill",
    "japanese": "スピアー"
  },
  "beheeyem": {
    "dex_id": 606,
    "english": "Beheeyem",
    "japanese": "オーベム"
  },
  "beldum": {
    "dex_id": 374,
    "english": "Beldum",
    "japanese": "ダンバル"
  },
  "bellibolt": {
    "dex_id": 939,
    "english": "Bellibolt",
    "japanese": "ハラバリー"
  },
  "bellossom": {
    "dex_id": 182,
    "english": "Bellossom",
    "japanese": "キレイハナ"
  },
  "bellsprout": {
    "dex_id": 69,
    "english": "Bellsprout",
    "japanese": "マダツボミ"
  },
  "bergmite": {
    "dex_id": 712,
    "english": "Bergmite",
    "japanese": "カチコール"
  },
  "bewear": {
    "dex_id": 760,
    "english": "Bewear",
    "japanese": "キテルグマ"
  },
  "bibarel": {
    "dex_id": 400,
    "english": "Bibarel",
    "japanese": "ビーダル"
  },
  "bidoof": {
    "dex_id": 399,
    "english": "Bidoof",
    "japanese": "ビッパ"
  },
  "binacle": {
    "dex_id": 688,
    "english": "Binacle",
    "japanese": "カメテテ"
  },
  "bisharp": {
    "dex_id": 625,
    "english": "Bisharp",
    "japanese": "キリキザン"
  },
  "blacephalon": {
    "dex_id": 806,
    "english": "Blacephalon",
    "japanese": "ズガドーン"
  },
  "blastoise": {
    "dex_id": 9,
    "english": "Blastoise",
    "japanese": "カメックス"
  },
  "blaziken": {
    "dex_id": 257,
    "english": "Blaziken",
    "japanese": "バシャーモ"
  },
  "blipbug": {
    "dex_id": 824,
    "english": "Blipbug",
    "japanese": "サッチムシ"
  },
  "blissey": {
    "dex_id": 242,
    "english": "Blissey",
    "japanese": "ハピナス"
  },
  "blitzle": {
    "dex_id": 522,
    "english": "Blitzle",
    "japanese": "シママ"
  },
  "boldore": {
    "dex_id": 525,
    "english": "Boldore",
    "japanese": "ガントル"
  },
  "boltund": {
    "dex_id": 836,
    "english": "Boltund",
    "japanese": "パルスワン"
  },
  "bombirdier": {
    "dex_id": 962,
    "english": "Bombirdier",
    "japanese": "オトシドリ"
  },
  "bonsly": {
    "dex_id": 438,
    "english": "Bonsly",
    "japanese": "ウソハチ"
  },
  "bouffalant": {
    "dex_id": 626,
    "english": "Bouffalant",
    "japanese": "バッフロン"
  },
  "bounsweet": {
    "dex_id": 761,
    "english": "Bounsweet",
    "japanese": "アマカジ"
  },
  "braixen": {
    "dex_id": 654,
    "english": "Braixen",
    "japanese": "テールナー"
  },
  "brambleghast": {
    "dex_id": 947,
    "english": "Brambleghast",
    "japanese": "アノホラグサ"
  },
  "bramblin": {
    "dex_id": 946,
    "english": "Bramblin",
    "japanese": "アノクサ"
  },
  "braviary": {
    "dex_id": 628,
    "english": "Braviary",
    "japanese": "ウォーグル"
  },
  "breloom": {
    "dex_id": 286,
    "english": "Breloom",
    "japanese": "キノガッサ"
  },
  "brionne": {
    "dex_id": 729,
    "english": "Brionne",
    "japanese": "オシャマリ"
  },
  "bronzong": {
    "dex_id": 437,
    "english": "Bronzong",
    "japanese": "ドータクン"
  },
  "bronzor": {
    "dex_id": 436,
    "english": "Bronzor",
    "japanese": "ドーミラー"
  },
  "brute bonnet": {
    "dex_id": 986,
    "english": "Brute Bonnet",
    "japanese": "アラブルタケ"
  },
  "brutebonnet": {
    "dex_id": 986,
    "english": "Brute Bonnet",
    "japanese": "アラブルタケ"
  },
  "bruxish": {
    "dex_id": 779,
    "english": "Bruxish",
    "japanese": "ハギギシリ"
  },
  "budew": {
    "dex_id": 406,
    "english": "Budew",
    "japanese": "スボミー"
  },
  "buizel": {
    "dex_id": 418,
    "english": "Buizel",
    "japanese": "ブイゼル"
  },
  "bulbasaur": {
    "dex_id": 1,
    "english": "Bulbasaur",
    "japanese": "フシギダネ"
  },
  "buneary": {
    "dex_id": 427,
    "english": "Buneary",
    "japanese": "ミミロル"
  },
  "bunnelby": {
    "dex_id": 659,
    "english": "Bunnelby",
    "japanese": "ホルビー"
  },
  "burmy": {
    "dex_id": 412,
    "english": "Burmy",
    "japanese": "ミノムッチ"
  },
  "butterfree": {
    "dex_id": 12,
    "english": "Butterfree",
    "japanese": "バタフリー"
  },
  "buzzwole": {
    "dex_id": 794,
    "english": "Buzzwole",
    "japanese": "マッシブーン"
  },
  "cacnea": {
    "dex_id": 331,
    "english": "Cacnea",
    "japanese": "サボネア"
  },
  "cacturne": {
    "dex_id": 332,
    "english": "Cacturne",
    "japanese": "ノクタス"
  },
  "calyrex": {
    "dex_id": 898,
    "english": "Calyrex",
    "japanese": "バドレックス"
  },
  "camerupt": {
    "dex_id": 323,
    "english": "Camerupt",
    "japanese": "バクーダ"
  },
  "capsakid": {
    "dex_id": 951,
    "english": "Capsakid",
    "japanese": "カプサイジ"
  },
  "carbink": {
    "dex_id": 703,
    "english": "Carbink",
    "japanese": "メレシー"
  },
  "carkol": {
    "dex_id": 838,
    "english": "Carkol",
    "japanese": "トロッゴン"
  },
  "carnivine": {
    "dex_id": 455,
    "english": "Carnivine",
    "japanese": "マスキッパ"
  },
  "carracosta": {
    "dex_id": 565,
    "english": "Carracosta",
    "japanese": "アバゴーラ"
  },
  "carvanha": {
    "dex_id": 318,
    "english": "Carvanha",
    "japanese": "キバニア"
  },
  "cascoon": {
    "dex_id": 268,
    "english": "Cascoon",
    "japanese": "マユルド"
  },
  "castform": {
    "dex_id": 351,
    "english": "Castform",
    "japanese": "ポワルン"
  },
  "caterpie": {
    "dex_id": 10,
    "english": "Caterpie",
    "japanese": "キャタピー"
  },
  "celebi": {
    "dex_id": 251,
    "english": "Celebi",
    "japanese": "セレビィ"
  },
  "celesteela": {
    "dex_id": 797,
    "english": "Celesteela",
    "japanese": "テッカグヤ"
  },
  "centiskorch": {
    "dex_id": 851,
    "english": "Centiskorch",
    "japanese": "マルヤクデ"
  },
  "ceruledge": {
    "dex_id": 937,
    "english": "Ceruledge",
    "japanese": "ソウブレイズ"
  },
  "cetitan": {
    "dex_id": 975,
    "english": "Cetitan",
    "japanese": "ハルクジラ"
  },
  "cetoddle": {
    "dex_id": 974,
    "english": "Cetoddle",
    "japanese": "アルクジラ"
  },
  "chandelure": {
    "dex_id": 609,
    "english": "Chandelure",
    "japanese": "シャンデラ"
  },
  "chansey": {
    "dex_id": 113,
    "english": "Chansey",
    "japanese": "ラッキー"
  },
  "charcadet": {
    "dex_id": 935,
    "english": "Charcadet",
    "japanese": "カルボウ"
  },
  "charizard": {
    "dex_id": 6,
    "english": "Charizard",
    "japanese": "リザードン"
  },
  "charjabug": {
    "dex_id": 737,
    "english": "Charjabug",
    "japanese": "デンヂムシ"
  },
  "charmander": {
    "dex_id": 4,
    "english": "Charmander",
    "japanese": "ヒトカゲ"
  },
  "charmeleon": {
    "dex_id": 5,
    "english": "Charmeleon",
    "japanese": "リザード"
  },
  "chatot": {
    "dex_id": 441,
    "english": "Chatot",
    "japanese": "ペラップ"
  },
  "cherrim": {
    "dex_id": 421,
    "english": "Cherrim",
    "japanese": "チェリム"
  },
  "cherubi": {
    "dex_id": 420,
    "english": "Cherubi",
    "japanese": "チェリンボ"
  },
  "chesnaught": {
    "dex_id": 652,
    "english": "Chesnaught",
    "japanese": "ブリガロン"
  },
  "chespin": {
    "dex_id": 650,
    "english": "Chespin",
    "japanese": "ハリマロン"
  },
  "chewtle": {
    "dex_id": 833,
    "english": "Chewtle",
    "japanese": "カムカメ"
  },
  "chi yu": {
    "dex_id": 1004,
    "english": "Chi-Yu",
    "japanese": "イーユイ"
  },
  "chien pao": {
    "dex_id": 1002,
    "english": "Chien-Pao",
    "japanese": "パオジアン"
  },
  "chienpao": {
    "dex_id": 1002,
    "english": "Chien-Pao",
    "japanese": "パオジアン"
  },
  "chikorita": {
    "dex_id": 152,
    "english": "Chikorita",
    "japanese": "チコリータ"
  },
  "chimchar": {
    "dex_id": 390,
    "english": "Chimchar",
    "japanese": "ヒコザル"
  },
  "chimecho": {
    "dex_id": 358,
    "english": "Chimecho",
    "japanese": "チリーン"
  },
  "chinchou": {
    "dex_id": 170,
    "english": "Chinchou",
    "japanese": "チョンチー"
  },
  "chingling": {
    "dex_id": 433,
    "english": "Chingling",
    "japanese": "リーシャン"
  },
  "chiyu": {
    "dex_id": 1004,
    "english": "Chi-Yu",
    "japanese": "イーユイ"
  },
  "cinccino": {
    "dex_id": 573,
    "english": "Cinccino",
    "japanese": "チラチーノ"
  },
  "cinderace": {
    "dex_id": 815,
    "english": "Cinderace",
    "japanese": "エースバーン"
  },
  "clamperl": {
    "dex_id": 366,
    "english": "Clamperl",
    "japanese": "パールル"
  },
  "clauncher": {
    "dex_id": 692,
    "english": "Clauncher",
    "japanese": "ウデッポウ"
  },
  "clawitzer": {
    "dex_id": 693,
    "english": "Clawitzer",
    "japanese": "ブロスター"
  },
  "claydol": {
    "dex_id": 344,
    "english": "Claydol",
    "japanese": "ネンドール"
  },
  "clefable": {
    "dex_id": 36,
    "english": "Clefable",
    "japanese": "ピクシー"
  },
  "clefairy": {
    "dex_id": 35,
    "english": "Clefairy",
    "japanese": "ピッピ"
  },
  "cleffa": {
    "dex_id": 173,
    "english": "Cleffa",
    "japanese": "ピィ"
  },
  "clobbopus": {
    "dex_id": 852,
    "english": "Clobbopus",
    "japanese": "タタッコ"
  },
  "clodsire": {
    "dex_id": 980,
    "english": "Clodsire",
    "japanese": "ドオー"
  },
  "cloyster": {
    "dex_id": 91,
    "english": "Cloyster",
    "japanese": "パルシェン"
  },
  "coalossal": {
    "dex_id": 839,
    "english": "Coalossal",
    "japanese": "セキタンザン"
  },
  "cobalion": {
    "dex_id": 638,
    "english": "Cobalion",
    "japanese": "コバルオン"
  },
  "cofagrigus": {
    "dex_id": 563,
    "english": "Cofagrigus",
    "japanese": "デスカーン"
  },
  "combee": {
    "dex_id": 415,
    "english": "Combee",
    "japanese": "ミツハニー"
  },
  "combusken": {
    "dex_id": 256,
    "english": "Combusken",
    "japanese": "ワカシャモ"
  },
  "comfey": {
    "dex_id": 764,
    "english": "Comfey",
    "japanese": "キュワワー"
  },
  "conkeldurr": {
    "dex_id": 534,
    "english": "Conkeldurr",
    "japanese": "ローブシン"
  },
  "copperajah": {
    "dex_id": 879,
    "english": "Copperajah",
    "japanese": "ダイオウドウ"
  },
  "corphish": {
    "dex_id": 341,
    "english": "Corphish",
    "japanese": "ヘイガニ"
  },
  "corsola": {
    "dex_id": 222,
    "english": "Corsola",
    "japanese": "サニーゴ"
  },
  "corviknight": {
    "dex_id": 823,
    "english": "Corviknight",
    "japanese": "アーマーガア"
  },
  "corvisquire": {
    "dex_id": 822,
    "english": "Corvisquire",
    "japanese": "アオガラス"
  },
  "cosmoem": {
    "dex_id": 790,
    "english": "Cosmoem",
    "japanese": "コスモウム"
  },
  "cosmog": {
    "dex_id": 789,
    "english": "Cosmog",
    "japanese": "コスモッグ"
  },
  "cottonee": {
    "dex_id": 546,
    "english": "Cottonee",
    "japanese": "モンメン"
  },
  "crabominable": {
    "dex_id": 740,
    "english": "Crabominable",
    "japanese": "ケケンカニ"
  },
  "crabrawler": {
    "dex_id": 739,
    "english": "Crabrawler",
    "japanese": "マケンカニ"
  },
  "cradily": {
    "dex_id": 346,
    "english": "Cradily",
    "japanese": "ユレイドル"
  },
  "cramorant": {
    "dex_id": 845,
    "english": "Cramorant",
    "japanese": "ウッウ"
  },
  "cranidos": {
    "dex_id": 408,
    "english": "Cranidos",
    "japanese": "ズガイドス"
  },
  "crawdaunt": {
    "dex_id": 342,
    "english": "Crawdaunt",
    "japanese": "シザリガー"
  },
  "cresselia": {
    "dex_id": 488,
    "english": "Cresselia",
    "japanese": "クレセリア"
  },
  "croagunk": {
    "dex_id": 453,
    "english": "Croagunk",
    "japanese": "グレッグル"
  },
  "crobat": {
    "dex_id": 169,
    "english": "Crobat",
    "japanese": "クロバット"
  },
  "crocalor": {
    "dex_id": 910,
    "english": "Crocalor",
    "japanese": "アチゲータ"
  },
  "croconaw": {
    "dex_id": 159,
    "english": "Croconaw",
    "japanese": "アリゲイツ"
  },
  "crustle": {
    "dex_id": 558,
    "english": "Crustle",
    "japanese": "イワパレス"
  },
  "cryogonal": {
    "dex_id": 615,
    "english": "Cryogonal",
    "japanese": "フリージオ"
  },
  "cubchoo": {
    "dex_id": 613,
    "english": "Cubchoo",
    "japanese": "クマシュン"
  },
  "cubone": {
    "dex_id": 104,
    "english": "Cubone",
    "japanese": "カラカラ"
  },
  "cufant": {
    "dex_id": 878,
    "english": "Cufant",
    "japanese": "ゾウドウ"
  },
  "cursola": {
    "dex_id": 864,
    "english": "Cursola",
    "japanese": "サニゴーン"
  },
  "cutiefly": {
    "dex_id": 742,
    "english": "Cutiefly",
    "japanese": "アブリー"
  },
  "cyclizar": {
    "dex_id": 967,
    "english": "Cyclizar",
    "japanese": "モトトカゲ"
  },
  "cyndaquil": {
    "dex_id": 155,
    "english": "Cyndaquil",
    "japanese": "ヒノアラシ"
  },
  "dachsbun": {
    "dex_id": 927,
    "english": "Dachsbun",
    "japanese": "バウッツェル"
  },
  "darkrai": {
    "dex_id": 491,
    "english": "Darkrai",
    "japanese": "ダークライ"
  },
  "darmanitan": {
    "dex_id": 555,
    "english": "Darmanitan",
    "japanese": "ヒヒダルマ"
  },
  "dartrix": {
    "dex_id": 723,
    "english": "Dartrix",
    "japanese": "フクスロー"
  },
  "darumaka": {
    "dex_id": 554,
    "english": "Darumaka",
    "japanese": "ダルマッカ"
  },
  "decidueye": {
    "dex_id": 724,
    "english": "Decidueye",
    "japanese": "ジュナイパー"
  },
  "dedenne": {
    "dex_id": 702,
    "english": "Dedenne",
    "japanese": "デデンネ"
  },
  "deerling": {
    "dex_id": 585,
    "english": "Deerling",
    "japanese": "シキジカ"
  },
  "deino": {
    "dex_id": 633,
    "english": "Deino",
    "japanese": "モノズ"
  },
  "delcatty": {
    "dex_id": 301,
    "english": "Delcatty",
    "japanese": "エネコロロ"
  },
  "delibird": {
    "dex_id": 225,
    "english": "Delibird",
    "japanese": "デリバード"
  },
  "delphox": {
    "dex_id": 655,
    "english": "Delphox",
    "japanese": "マフォクシー"
  },
  "deoxys": {
    "dex_id": 386,
    "english": "Deoxys",
    "japanese": "デオキシス"
  },
  "dewgong": {
    "dex_id": 87,
    "english": "Dewgong",
    "japanese": "ジュゴン"
  },
  "dewott": {
    "dex_id": 502,
    "english": "Dewott",
    "japanese": "フタチマル"
  },
  "dewpider": {
    "dex_id": 751,
    "english": "Dewpider",
    "japanese": "シズクモ"
  },
  "dhelmise": {
    "dex_id": 781,
    "english": "Dhelmise",
    "japanese": "ダダリン"
  },
  "dialga": {
    "dex_id": 483,
    "english": "Dialga",
    "japanese": "ディアルガ"
  },
  "diancie": {
    "dex_id": 719,
    "english": "Diancie",
    "japanese": "ディアンシー"
  },
  "diggersby": {
    "dex_id": 660,
    "english": "Diggersby",
    "japanese": "ホルード"
  },
  "diglett": {
    "dex_id": 50,
    "english": "Diglett",
    "japanese": "ディグダ"
  },
  "dipplin": {
    "dex_id": 1011,
    "english": "Dipplin",
    "japanese": "カミッチュ"
  },
  "ditto": {
    "dex_id": 132,
    "english": "Ditto",
    "japanese": "メタモン"
  },
  "dodrio": {
    "dex_id": 85,
    "english": "Dodrio",
    "japanese": "ドードリオ"
  },
  "doduo": {
    "dex_id": 84,
    "english": "Doduo",
    "japanese": "ドードー"
  },
  "dolliv": {
    "dex_id": 929,
    "english": "Dolliv",
    "japanese": "オリーニョ"
  },
  "dondozo": {
    "dex_id": 977,
    "english": "Dondozo",
    "japanese": "ヘイラッシャ"
  },
  "donphan": {
    "dex_id": 232,
    "english": "Donphan",
    "japanese": "ドンファン"
  },
  "dottler": {
    "dex_id": 825,
    "english": "Dottler",
    "japanese": "レドームシ"
  },
  "doublade": {
    "dex_id": 680,
    "english": "Doublade",
    "japanese": "ニダンギル"
  },
  "dracovish": {
    "dex_id": 882,
    "english": "Dracovish",
    "japanese": "ウオノラゴン"
  },
  "dracozolt": {
    "dex_id": 880,
    "english": "Dracozolt",
    "japanese": "パッチラゴン"
  },
  "dragalge": {
    "dex_id": 691,
    "english": "Dragalge",
    "japanese": "ドラミドロ"
  },
  "dragapult": {
    "dex_id": 887,
    "english": "Dragapult",
    "japanese": "ドラパルト"
  },
  "dragonair": {
    "dex_id": 148,
    "english": "Dragonair",
    "japanese": "ハクリュー"
  },
  "dragonite": {
    "dex_id": 149,
    "english": "Dragonite",
    "japanese": "カイリュー"
  },
  "drakloak": {
    "dex_id": 886,
    "english": "Drakloak",
    "japanese": "ドロンチ"
  },
  "drampa": {
    "dex_id": 780,
    "english": "Drampa",
    "japanese": "ジジーロン"
  },
  "drapion": {
    "dex_id": 452,
    "english": "Drapion",
    "japanese": "ドラピオン"
  },
  "dratini": {
    "dex_id": 147,
    "english": "Dratini",
    "japanese": "ミニリュウ"
  },
  "drednaw": {
    "dex_id": 834,
    "english": "Drednaw",
    "japanese": "カジリガメ"
  },
  "dreepy": {
    "dex_id": 885,
    "english": "Dreepy",
    "japanese": "ドラメシヤ"
  },
  "drifblim": {
    "dex_id": 426,
    "english": "Drifblim",
    "japanese": "フワライド"
  },
  "drifloon": {
    "dex_id": 425,
    "english": "Drifloon",
    "japanese": "フワンテ"
  },
  "drilbur": {
    "dex_id": 529,
    "english": "Drilbur",
    "japanese": "モグリュー"
  },
  "drizzile": {
    "dex_id": 817,
    "english": "Drizzile",
    "japanese": "ジメレオン"
  },
  "drowzee": {
    "dex_id": 96,
    "english": "Drowzee",
    "japanese": "スリープ"
  },
  "druddigon": {
    "dex_id": 621,
    "english": "Druddigon",
    "japanese": "クリムガン"
  },
  "dubwool": {
    "dex_id": 832,
    "english": "Dubwool",
    "japanese": "バイウールー"
  },
  "ducklett": {
    "dex_id": 580,
    "english": "Ducklett",
    "japanese": "コアルヒー"
  },
  "dudunsparce": {
    "dex_id": 982,
    "english": "Dudunsparce",
    "japanese": "ノココッチ"
  },
  "dugtrio": {
    "dex_id": 51,
    "english": "Dugtrio",
    "japanese": "ダグトリオ"
  },
  "dunsparce": {
    "dex_id": 206,
    "english": "Dunsparce",
    "japanese": "ノコッチ"
  },
  "duosion": {
    "dex_id": 578,
    "english": "Duosion",
    "japanese": "ダブラン"
  },
  "duraludon": {
    "dex_id": 884,
    "english": "Duraludon",
    "japanese": "ジュラルドン"
  },
  "durant": {
    "dex_id": 632,
    "english": "Durant",
    "japanese": "アイアント"
  },
  "dusclops": {
    "dex_id": 356,
    "english": "Dusclops",
    "japanese": "サマヨール"
  },
  "dusknoir": {
    "dex_id": 477,
    "english": "Dusknoir",
    "japanese": "ヨノワール"
  },
  "duskull": {
    "dex_id": 355,
    "english": "Duskull",
    "japanese": "ヨマワル"
  },
  "dustox": {
    "dex_id": 269,
    "english": "Dustox",
    "japanese": "ドクケイル"
  },
  "dwebble": {
    "dex_id": 557,
    "english": "Dwebble",
    "japanese": "イシズマイ"
  },
  "eelektrik": {
    "dex_id": 603,
    "english": "Eelektrik",
    "japanese": "シビビール"
  },
  "eelektross": {
    "dex_id": 604,
    "english": "Eelektross",
    "japanese": "シビルドン"
  },
  "eevee": {
    "dex_id": 133,
    "english": "Eevee",
    "japanese": "イーブイ"
  },
  "eiscue": {
    "dex_id": 875,
    "english": "Eiscue",
    "japanese": "コオリッポ"
  },
  "ekans": {
    "dex_id": 23,
    "english": "Ekans",
    "japanese": "アーボ"
  },
  "eldegoss": {
    "dex_id": 830,
    "english": "Eldegoss",
    "japanese": "ワタシラガ"
  },
  "electabuzz": {
    "dex_id": 125,
    "english": "Electabuzz",
    "japanese": "エレブー"
  },
  "electivire": {
    "dex_id": 466,
    "english": "Electivire",
    "japanese": "エレキブル"
  },
  "electrike": {
    "dex_id": 309,
    "english": "Electrike",
    "japanese": "ラクライ"
  },
  "electrode": {
    "dex_id": 101,
    "english": "Electrode",
    "japanese": "マルマイン"
  },
  "elekid": {
    "dex_id": 239,
    "english": "Elekid",
    "japanese": "エレキッド"
  },
  "elgyem": {
    "dex_id": 605,
    "english": "Elgyem",
    "japanese": "リグレー"
  },
  "emboar": {
    "dex_id": 500,
    "english": "Emboar",
    "japanese": "エンブオー"
  },
  "emolga": {
    "dex_id": 587,
    "english": "Emolga",
    "japanese": "エモンガ"
  },
  "empoleon": {
    "dex_id": 395,
    "english": "Empoleon",
    "japanese": "エンペルト"
  },
  "enamorus": {
    "dex_id": 905,
    "english": "Enamorus",
    "japanese": "ラブトロス"
  },
  "entei": {
    "dex_id": 244,
    "english": "Entei",
    "japanese": "エンテイ"
  },
  "escavalier": {
    "dex_id": 589,
    "english": "Escavalier",
    "japanese": "シュバルゴ"
  },
  "espathra": {
    "dex_id": 956,
    "english": "Espathra",
    "japanese": "クエスパトラ"
  },
  "espeon": {
    "dex_id": 196,
    "english": "Espeon",
    "japanese": "エーフィ"
  },
  "espurr": {
    "dex_id": 677,
    "english": "Espurr",
    "japanese": "ニャスパー"
  },
  "eternatus": {
    "dex_id": 890,
    "english": "Eternatus",
    "japanese": "ムゲンダイナ"
  },
  "excadrill": {
    "dex_id": 530,
    "english": "Excadrill",
    "japanese": "ドリュウズ"
  },
  "exeggcute": {
    "dex_id": 102,
    "english": "Exeggcute",
    "japanese": "タマタマ"
  },
  "exeggutor": {
    "dex_id": 103,
    "english": "Exeggutor",
    "japanese": "ナッシー"
  },
  "exploud": {
    "dex_id": 295,
    "english": "Exploud",
    "japanese": "バクオング"
  },
  "falinks": {
    "dex_id": 870,
    "english": "Falinks",
    "japanese": "タイレーツ"
  },
  "farfetch d": {
    "dex_id": 83,
    "english": "Farfetch’d",
    "japanese": "カモネギ"
  },
  "farfetchd": {
    "dex_id": 83,
    "english": "Farfetch’d",
    "japanese": "カモネギ"
  },
  "farigiraf": {
    "dex_id": 981,
    "english": "Farigiraf",
    "japanese": "リキキリン"
  },
  "fearow": {
    "dex_id": 22,
    "english": "Fearow",
    "japanese": "オニドリル"
  },
  "feebas": {
    "dex_id": 349,
    "english": "Feebas",
    "japanese": "ヒンバス"
  },
  "fennekin": {
    "dex_id": 653,
    "english": "Fennekin",
    "japanese": "フォッコ"
  },
  "feraligatr": {
    "dex_id": 160,
    "english": "Feraligatr",
    "japanese": "オーダイル"
  },
  "ferroseed": {
    "dex_id": 597,
    "english": "Ferroseed",
    "japanese": "テッシード"
  },
  "ferrothorn": {
    "dex_id": 598,
    "english": "Ferrothorn",
    "japanese": "ナットレイ"
  },
  "fezandipiti": {
    "dex_id": 1016,
    "english": "Fezandipiti",
    "japanese": "キチキギス"
  },
  "fidough": {
    "dex_id": 926,
    "english": "Fidough",
    "japanese": "パピモッチ"
  },
  "finizen": {
    "dex_id": 963,
    "english": "Finizen",
    "japanese": "ナミイルカ"
  },
  "finneon": {
    "dex_id": 456,
    "english": "Finneon",
    "japanese": "ケイコウオ"
  },
  "flaaffy": {
    "dex_id": 180,
    "english": "Flaaffy",
    "japanese": "モココ"
  },
  "flab b": {
    "dex_id": 669,
    "english": "Flabébé",
    "japanese": "フラベベ"
  },
  "flabebe": {
    "dex_id": 669,
    "english": "Flabébé",
    "japanese": "フラベベ"
  },
  "flamigo": {
    "dex_id": 973,
    "english": "Flamigo",
    "japanese": "カラミンゴ"
  },
  "flapple": {
    "dex_id": 841,
    "english": "Flapple",
    "japanese": "アップリュー"
  },
  "flareon": {
    "dex_id": 136,
    "english": "Flareon",
    "japanese": "ブースター"
  },
  "fletchinder": {
    "dex_id": 662,
    "english": "Fletchinder",
    "japanese": "ヒノヤコマ"
  },
  "fletchling": {
    "dex_id": 661,
    "english": "Fletchling",
    "japanese": "ヤヤコマ"
  },
  "flittle": {
    "dex_id": 955,
    "english": "Flittle",
    "japanese": "ヒラヒナ"
  },
  "floatzel": {
    "dex_id": 419,
    "english": "Floatzel",
    "japanese": "フローゼル"
  },
  "floette": {
    "dex_id": 670,
    "english": "Floette",
    "japanese": "フラエッテ"
  },
  "floragato": {
    "dex_id": 907,
    "english": "Floragato",
    "japanese": "ニャローテ"
  },
  "florges": {
    "dex_id": 671,
    "english": "Florges",
    "japanese": "フラージェス"
  },
  "flutter mane": {
    "dex_id": 987,
    "english": "Flutter Mane",
    "japanese": "ハバタクカミ"
  },
  "fluttermane": {
    "dex_id": 987,
    "english": "Flutter Mane",
    "japanese": "ハバタクカミ"
  },
  "flygon": {
    "dex_id": 330,
    "english": "Flygon",
    "japanese": "フライゴン"
  },
  "fomantis": {
    "dex_id": 753,
    "english": "Fomantis",
    "japanese": "カリキリ"
  },
  "foongus": {
    "dex_id": 590,
    "english": "Foongus",
    "japanese": "タマゲタケ"
  },
  "forretress": {
    "dex_id": 205,
    "english": "Forretress",
    "japanese": "フォレトス"
  },
  "fraxure": {
    "dex_id": 611,
    "english": "Fraxure",
    "japanese": "オノンド"
  },
  "frigibax": {
    "dex_id": 996,
    "english": "Frigibax",
    "japanese": "セビエ"
  },
  "frillish": {
    "dex_id": 592,
    "english": "Frillish",
    "japanese": "プルリル"
  },
  "froakie": {
    "dex_id": 656,
    "english": "Froakie",
    "japanese": "ケロマツ"
  },
  "frogadier": {
    "dex_id": 657,
    "english": "Frogadier",
    "japanese": "ゲコガシラ"
  },
  "froslass": {
    "dex_id": 478,
    "english": "Froslass",
    "japanese": "ユキメノコ"
  },
  "frosmoth": {
    "dex_id": 873,
    "english": "Frosmoth",
    "japanese": "モスノウ"
  },
  "fuecoco": {
    "dex_id": 909,
    "english": "Fuecoco",
    "japanese": "ホゲータ"
  },
  "furfrou": {
    "dex_id": 676,
    "english": "Furfrou",
    "japanese": "トリミアン"
  },
  "furret": {
    "dex_id": 162,
    "english": "Furret",
    "japanese": "オオタチ"
  },
  "gabite": {
    "dex_id": 444,
    "english": "Gabite",
    "japanese": "ガバイト"
  },
  "gallade": {
    "dex_id": 475,
    "english": "Gallade",
    "japanese": "エルレイド"
  },
  "galvantula": {
    "dex_id": 596,
    "english": "Galvantula",
    "japanese": "デンチュラ"
  },
  "garbodor": {
    "dex_id": 569,
    "english": "Garbodor",
    "japanese": "ダストダス"
  },
  "garchomp": {
    "dex_id": 445,
    "english": "Garchomp",
    "japanese": "ガブリアス"
  },
  "gardevoir": {
    "dex_id": 282,
    "english": "Gardevoir",
    "japanese": "サーナイト"
  },
  "garganacl": {
    "dex_id": 934,
    "english": "Garganacl",
    "japanese": "キョジオーン"
  },
  "gastly": {
    "dex_id": 92,
    "english": "Gastly",
    "japanese": "ゴース"
  },
  "gastrodon": {
    "dex_id": 423,
    "english": "Gastrodon",
    "japanese": "トリトドン"
  },
  "genesect": {
    "dex_id": 649,
    "english": "Genesect",
    "japanese": "ゲノセクト"
  },
  "gengar": {
    "dex_id": 94,
    "english": "Gengar",
    "japanese": "ゲンガー"
  },
  "geodude": {
    "dex_id": 74,
    "english": "Geodude",
    "japanese": "イシツブテ"
  },
  "gholdengo": {
    "dex_id": 1000,
    "english": "Gholdengo",
    "japanese": "サーフゴー"
  },
  "gible": {
    "dex_id": 443,
    "english": "Gible",
    "japanese": "フカマル"
  },
  "gigalith": {
    "dex_id": 526,
    "english": "Gigalith",
    "japanese": "ギガイアス"
  },
  "gimmighoul": {
    "dex_id": 999,
    "english": "Gimmighoul",
    "japanese": "コレクレー"
  },
  "girafarig": {
    "dex_id": 203,
    "english": "Girafarig",
    "japanese": "キリンリキ"
  },
  "giratina": {
    "dex_id": 487,
    "english": "Giratina",
    "japanese": "ギラティナ"
  },
  "glaceon": {
    "dex_id": 471,
    "english": "Glaceon",
    "japanese": "グレイシア"
  },
  "glalie": {
    "dex_id": 362,
    "english": "Glalie",
    "japanese": "オニゴーリ"
  },
  "glameow": {
    "dex_id": 431,
    "english": "Glameow",
    "japanese": "ニャルマー"
  },
  "glastrier": {
    "dex_id": 896,
    "english": "Glastrier",
    "japanese": "ブリザポス"
  },
  "gligar": {
    "dex_id": 207,
    "english": "Gligar",
    "japanese": "グライガー"
  },
  "glimmet": {
    "dex_id": 969,
    "english": "Glimmet",
    "japanese": "キラーメ"
  },
  "glimmora": {
    "dex_id": 970,
    "english": "Glimmora",
    "japanese": "キラフロル"
  },
  "gliscor": {
    "dex_id": 472,
    "english": "Gliscor",
    "japanese": "グライオン"
  },
  "gloom": {
    "dex_id": 44,
    "english": "Gloom",
    "japanese": "クサイハナ"
  },
  "gogoat": {
    "dex_id": 673,
    "english": "Gogoat",
    "japanese": "ゴーゴート"
  },
  "golbat": {
    "dex_id": 42,
    "english": "Golbat",
    "japanese": "ゴルバット"
  },
  "goldeen": {
    "dex_id": 118,
    "english": "Goldeen",
    "japanese": "トサキント"
  },
  "golduck": {
    "dex_id": 55,
    "english": "Golduck",
    "japanese": "ゴルダック"
  },
  "golem": {
    "dex_id": 76,
    "english": "Golem",
    "japanese": "ゴローニャ"
  },
  "golett": {
    "dex_id": 622,
    "english": "Golett",
    "japanese": "ゴビット"
  },
  "golisopod": {
    "dex_id": 768,
    "english": "Golisopod",
    "japanese": "グソクムシャ"
  },
  "golurk": {
    "dex_id": 623,
    "english": "Golurk",
    "japanese": "ゴルーグ"
  },
  "goodra": {
    "dex_id": 706,
    "english": "Goodra",
    "japanese": "ヌメルゴン"
  },
  "goomy": {
    "dex_id": 704,
    "english": "Goomy",
    "japanese": "ヌメラ"
  },
  "gorebyss": {
    "dex_id": 368,
    "english": "Gorebyss",
    "japanese": "サクラビス"
  },
  "gossifleur": {
    "dex_id": 829,
    "english": "Gossifleur",
    "japanese": "ヒメンカ"
  },
  "gothita": {
    "dex_id": 574,
    "english": "Gothita",
    "japanese": "ゴチム"
  },
  "gothitelle": {
    "dex_id": 576,
    "english": "Gothitelle",
    "japanese": "ゴチルゼル"
  },
  "gothorita": {
    "dex_id": 575,
    "english": "Gothorita",
    "japanese": "ゴチミル"
  },
  "gouging fire": {
    "dex_id": 1020,
    "english": "Gouging Fire",
    "japanese": "ウガツホムラ"
  },
  "gougingfire": {
    "dex_id": 1020,
    "english": "Gouging Fire",
    "japanese": "ウガツホムラ"
  },
  "gourgeist": {
    "dex_id": 711,
    "english": "Gourgeist",
    "japanese": "パンプジン"
  },
  "grafaiai": {
    "dex_id": 945,
    "english": "Grafaiai",
    "japanese": "タギングル"
  },
  "granbull": {
    "dex_id": 210,
    "english": "Granbull",
    "japanese": "グランブル"
  },
  "grapploct": {
    "dex_id": 853,
    "english": "Grapploct",
    "japanese": "オトスパス"
  },
  "graveler": {
    "dex_id": 75,
    "english": "Graveler",
    "japanese": "ゴローン"
  },
  "great tusk": {
    "dex_id": 984,
    "english": "Great Tusk",
    "japanese": "イダイナキバ"
  },
  "greattusk": {
    "dex_id": 984,
    "english": "Great Tusk",
    "japanese": "イダイナキバ"
  },
  "greavard": {
    "dex_id": 971,
    "english": "Greavard",
    "japanese": "ボチ"
  },
  "greedent": {
    "dex_id": 820,
    "english": "Greedent",
    "japanese": "ヨクバリス"
  },
  "greninja": {
    "dex_id": 658,
    "english": "Greninja",
    "japanese": "ゲッコウガ"
  },
  "grimer": {
    "dex_id": 88,
    "english": "Grimer",
    "japanese": "ベトベター"
  },
  "grimmsnarl": {
    "dex_id": 861,
    "english": "Grimmsnarl",
    "japanese": "オーロンゲ"
  },
  "grookey": {
    "dex_id": 810,
    "english": "Grookey",
    "japanese": "サルノリ"
  },
  "grotle": {
    "dex_id": 388,
    "english": "Grotle",
    "japanese": "ハヤシガメ"
  },
  "groudon": {
    "dex_id": 383,
    "english": "Groudon",
    "japanese": "グラードン"
  },
  "grovyle": {
    "dex_id": 253,
    "english": "Grovyle",
    "japanese": "ジュプトル"
  },
  "growlithe": {
    "dex_id": 58,
    "english": "Growlithe",
    "japanese": "ガーディ"
  },
  "grubbin": {
    "dex_id": 736,
    "english": "Grubbin",
    "japanese": "アゴジムシ"
  },
  "grumpig": {
    "dex_id": 326,
    "english": "Grumpig",
    "japanese": "ブーピッグ"
  },
  "gulpin": {
    "dex_id": 316,
    "english": "Gulpin",
    "japanese": "ゴクリン"
  },
  "gumshoos": {
    "dex_id": 735,
    "english": "Gumshoos",
    "japanese": "デカグース"
  },
  "gurdurr": {
    "dex_id": 533,
    "english": "Gurdurr",
    "japanese": "ドテッコツ"
  },
  "guzzlord": {
    "dex_id": 799,
    "english": "Guzzlord",
    "japanese": "アクジキング"
  },
  "gyarados": {
    "dex_id": 130,
    "english": "Gyarados",
    "japanese": "ギャラドス"
  },
  "hakamo o": {
    "dex_id": 783,
    "english": "Hakamo-o",
    "japanese": "ジャランゴ"
  },
  "hakamoo": {
    "dex_id": 783,
    "english": "Hakamo-o",
    "japanese": "ジャランゴ"
  },
  "happiny": {
    "dex_id": 440,
    "english": "Happiny",
    "japanese": "ピンプク"
  },
  "hariyama": {
    "dex_id": 297,
    "english": "Hariyama",
    "japanese": "ハリテヤマ"
  },
  "hatenna": {
    "dex_id": 856,
    "english": "Hatenna",
    "japanese": "ミブリム"
  },
  "hatterene": {
    "dex_id": 858,
    "english": "Hatterene",
    "japanese": "ブリムオン"
  },
  "hattrem": {
    "dex_id": 857,
    "english": "Hattrem",
    "japanese": "テブリム"
  },
  "haunter": {
    "dex_id": 93,
    "english": "Haunter",
    "japanese": "ゴースト"
  },
  "hawlucha": {
    "dex_id": 701,
    "english": "Hawlucha",
    "japanese": "ルチャブル"
  },
  "haxorus": {
    "dex_id": 612,
    "english": "Haxorus",
    "japanese": "オノノクス"
  },
  "heatmor": {
    "dex_id": 631,
    "english": "Heatmor",
    "japanese": "クイタラン"
  },
  "heatran": {
    "dex_id": 485,
    "english": "Heatran",
    "japanese": "ヒードラン"
  },
  "heliolisk": {
    "dex_id": 695,
    "english": "Heliolisk",
    "japanese": "エレザード"
  },
  "helioptile": {
    "dex_id": 694,
    "english": "Helioptile",
    "japanese": "エリキテル"
  },
  "heracross": {
    "dex_id": 214,
    "english": "Heracross",
    "japanese": "ヘラクロス"
  },
  "herdier": {
    "dex_id": 507,
    "english": "Herdier",
    "japanese": "ハーデリア"
  },
  "hippopotas": {
    "dex_id": 449,
    "english": "Hippopotas",
    "japanese": "ヒポポタス"
  },
  "hippowdon": {
    "dex_id": 450,
    "english": "Hippowdon",
    "japanese": "カバルドン"
  },
  "hitmonchan": {
    "dex_id": 107,
    "english": "Hitmonchan",
    "japanese": "エビワラー"
  },
  "hitmonlee": {
    "dex_id": 106,
    "english": "Hitmonlee",
    "japanese": "サワムラー"
  },
  "hitmontop": {
    "dex_id": 237,
    "english": "Hitmontop",
    "japanese": "カポエラー"
  },
  "ho oh": {
    "dex_id": 250,
    "english": "Ho-Oh",
    "japanese": "ホウオウ"
  },
  "honchkrow": {
    "dex_id": 430,
    "english": "Honchkrow",
    "japanese": "ドンカラス"
  },
  "honedge": {
    "dex_id": 679,
    "english": "Honedge",
    "japanese": "ヒトツキ"
  },
  "hooh": {
    "dex_id": 250,
    "english": "Ho-Oh",
    "japanese": "ホウオウ"
  },
  "hoopa": {
    "dex_id": 720,
    "english": "Hoopa",
    "japanese": "フーパ"
  },
  "hoothoot": {
    "dex_id": 163,
    "english": "Hoothoot",
    "japanese": "ホーホー"
  },
  "hoppip": {
    "dex_id": 187,
    "english": "Hoppip",
    "japanese": "ハネッコ"
  },
  "horsea": {
    "dex_id": 116,
    "english": "Horsea",
    "japanese": "タッツー"
  },
  "houndoom": {
    "dex_id": 229,
    "english": "Houndoom",
    "japanese": "ヘルガー"
  },
  "houndour": {
    "dex_id": 228,
    "english": "Houndour",
    "japanese": "デルビル"
  },
  "houndstone": {
    "dex_id": 972,
    "english": "Houndstone",
    "japanese": "ハカドッグ"
  },
  "huntail": {
    "dex_id": 367,
    "english": "Huntail",
    "japanese": "ハンテール"
  },
  "hydrapple": {
    "dex_id": 1019,
    "english": "Hydrapple",
    "japanese": "カミツオロチ"
  },
  "hydreigon": {
    "dex_id": 635,
    "english": "Hydreigon",
    "japanese": "サザンドラ"
  },
  "hypno": {
    "dex_id": 97,
    "english": "Hypno",
    "japanese": "スリーパー"
  },
  "igglybuff": {
    "dex_id": 174,
    "english": "Igglybuff",
    "japanese": "ププリン"
  },
  "illumise": {
    "dex_id": 314,
    "english": "Illumise",
    "japanese": "イルミーゼ"
  },
  "impidimp": {
    "dex_id": 859,
    "english": "Impidimp",
    "japanese": "ベロバー"
  },
  "incineroar": {
    "dex_id": 727,
    "english": "Incineroar",
    "japanese": "ガオガエン"
  },
  "indeedee": {
    "dex_id": 876,
    "english": "Indeedee",
    "japanese": "イエッサン"
  },
  "infernape": {
    "dex_id": 392,
    "english": "Infernape",
    "japanese": "ゴウカザル"
  },
  "inkay": {
    "dex_id": 686,
    "english": "Inkay",
    "japanese": "マーイーカ"
  },
  "inteleon": {
    "dex_id": 818,
    "english": "Inteleon",
    "japanese": "インテレオン"
  },
  "iron boulder": {
    "dex_id": 1022,
    "english": "Iron Boulder",
    "japanese": "テツノイワオ"
  },
  "iron bundle": {
    "dex_id": 991,
    "english": "Iron Bundle",
    "japanese": "テツノツツミ"
  },
  "iron crown": {
    "dex_id": 1023,
    "english": "Iron Crown",
    "japanese": "テツノカシラ"
  },
  "iron hands": {
    "dex_id": 992,
    "english": "Iron Hands",
    "japanese": "テツノカイナ"
  },
  "iron jugulis": {
    "dex_id": 993,
    "english": "Iron Jugulis",
    "japanese": "テツノコウベ"
  },
  "iron leaves": {
    "dex_id": 1010,
    "english": "Iron Leaves",
    "japanese": "テツノイサハ"
  },
  "iron moth": {
    "dex_id": 994,
    "english": "Iron Moth",
    "japanese": "テツノドクガ"
  },
  "iron thorns": {
    "dex_id": 995,
    "english": "Iron Thorns",
    "japanese": "テツノイバラ"
  },
  "iron treads": {
    "dex_id": 990,
    "english": "Iron Treads",
    "japanese": "テツノワダチ"
  },
  "iron valiant": {
    "dex_id": 1006,
    "english": "Iron Valiant",
    "japanese": "テツノブジン"
  },
  "ironboulder": {
    "dex_id": 1022,
    "english": "Iron Boulder",
    "japanese": "テツノイワオ"
  },
  "ironbundle": {
    "dex_id": 991,
    "english": "Iron Bundle",
    "japanese": "テツノツツミ"
  },
  "ironcrown": {
    "dex_id": 1023,
    "english": "Iron Crown",
    "japanese": "テツノカシラ"
  },
  "ironhands": {
    "dex_id": 992,
    "english": "Iron Hands",
    "japanese": "テツノカイナ"
  },
  "ironjugulis": {
    "dex_id": 993,
    "english": "Iron Jugulis",
    "japanese": "テツノコウベ"
  },
  "ironleaves": {
    "dex_id": 1010,
    "english": "Iron Leaves",
    "japanese": "テツノイサハ"
  },
  "ironmoth": {
    "dex_id": 994,
    "english": "Iron Moth",
    "japanese": "テツノドクガ"
  },
  "ironthorns": {
    "dex_id": 995,
    "english": "Iron Thorns",
    "japanese": "テツノイバラ"
  },
  "irontreads": {
    "dex_id": 990,
    "english": "Iron Treads",
    "japanese": "テツノワダチ"
  },
  "ironvaliant": {
    "dex_id": 1006,
    "english": "Iron Valiant",
    "japanese": "テツノブジン"
  },
  "ivysaur": {
    "dex_id": 2,
    "english": "Ivysaur",
    "japanese": "フシギソウ"
  },
  "jangmo o": {
    "dex_id": 782,
    "english": "Jangmo-o",
    "japanese": "ジャラコ"
  },
  "jangmoo": {
    "dex_id": 782,
    "english": "Jangmo-o",
    "japanese": "ジャラコ"
  },
  "jellicent": {
    "dex_id": 593,
    "english": "Jellicent",
    "japanese": "ブルンゲル"
  },
  "jigglypuff": {
    "dex_id": 39,
    "english": "Jigglypuff",
    "japanese": "プリン"
  },
  "jirachi": {
    "dex_id": 385,
    "english": "Jirachi",
    "japanese": "ジラーチ"
  },
  "jolteon": {
    "dex_id": 135,
    "english": "Jolteon",
    "japanese": "サンダース"
  },
  "joltik": {
    "dex_id": 595,
    "english": "Joltik",
    "japanese": "バチュル"
  },
  "jumpluff": {
    "dex_id": 189,
    "english": "Jumpluff",
    "japanese": "ワタッコ"
  },
  "jynx": {
    "dex_id": 124,
    "english": "Jynx",
    "japanese": "ルージュラ"
  },
  "kabuto": {
    "dex_id": 140,
    "english": "Kabuto",
    "japanese": "カブト"
  },
  "kabutops": {
    "dex_id": 141,
    "english": "Kabutops",
    "japanese": "カブトプス"
  },
  "kadabra": {
    "dex_id": 64,
    "english": "Kadabra",
    "japanese": "ユンゲラー"
  },
  "kakuna": {
    "dex_id": 14,
    "english": "Kakuna",
    "japanese": "コクーン"
  },
  "kangaskhan": {
    "dex_id": 115,
    "english": "Kangaskhan",
    "japanese": "ガルーラ"
  },
  "karrablast": {
    "dex_id": 588,
    "english": "Karrablast",
    "japanese": "カブルモ"
  },
  "kartana": {
    "dex_id": 798,
    "english": "Kartana",
    "japanese": "カミツルギ"
  },
  "kecleon": {
    "dex_id": 352,
    "english": "Kecleon",
    "japanese": "カクレオン"
  },
  "keldeo": {
    "dex_id": 647,
    "english": "Keldeo",
    "japanese": "ケルディオ"
  },
  "kilowattrel": {
    "dex_id": 941,
    "english": "Kilowattrel",
    "japanese": "タイカイデン"
  },
  "kingambit": {
    "dex_id": 983,
    "english": "Kingambit",
    "japanese": "ドドゲザン"
  },
  "kingdra": {
    "dex_id": 230,
    "english": "Kingdra",
    "japanese": "キングドラ"
  },
  "kingler": {
    "dex_id": 99,
    "english": "Kingler",
    "japanese": "キングラー"
  },
  "kirlia": {
    "dex_id": 281,
    "english": "Kirlia",
    "japanese": "キルリア"
  },
  "klang": {
    "dex_id": 600,
    "english": "Klang",
    "japanese": "ギギアル"
  },
  "klawf": {
    "dex_id": 950,
    "english": "Klawf",
    "japanese": "ガケガニ"
  },
  "kleavor": {
    "dex_id": 900,
    "english": "Kleavor",
    "japanese": "バサギリ"
  },
  "klefki": {
    "dex_id": 707,
    "english": "Klefki",
    "japanese": "クレッフィ"
  },
  "klink": {
    "dex_id": 599,
    "english": "Klink",
    "japanese": "ギアル"
  },
  "klinklang": {
    "dex_id": 601,
    "english": "Klinklang",
    "japanese": "ギギギアル"
  },
  "koffing": {
    "dex_id": 109,
    "english": "Koffing",
    "japanese": "ドガース"
  },
  "komala": {
    "dex_id": 775,
    "english": "Komala",
    "japanese": "ネッコアラ"
  },
  "kommo o": {
    "dex_id": 784,
    "english": "Kommo-o",
    "japanese": "ジャラランガ"
  },
  "kommoo": {
    "dex_id": 784,
    "english": "Kommo-o",
    "japanese": "ジャラランガ"
  },
  "koraidon": {
    "dex_id": 1007,
    "english": "Koraidon",
    "japanese": "コライドン"
  },
  "krabby": {
    "dex_id": 98,
    "english": "Krabby",
    "japanese": "クラブ"
  },
  "kricketot": {
    "dex_id": 401,
    "english": "Kricketot",
    "japanese": "コロボーシ"
  },
  "kricketune": {
    "dex_id": 402,
    "english": "Kricketune",
    "japanese": "コロトック"
  },
  "krokorok": {
    "dex_id": 552,
    "english": "Krokorok",
    "japanese": "ワルビル"
  },
  "krookodile": {
    "dex_id": 553,
    "english": "Krookodile",
    "japanese": "ワルビアル"
  },
  "kubfu": {
    "dex_id": 891,
    "english": "Kubfu",
    "japanese": "ダクマ"
  },
  "kyogre": {
    "dex_id": 382,
    "english": "Kyogre",
    "japanese": "カイオーガ"
  },
  "kyurem": {
    "dex_id": 646,
    "english": "Kyurem",
    "japanese": "キュレム"
  },
  "lairon": {
    "dex_id": 305,
    "english": "Lairon",
    "japanese": "コドラ"
  },
  "lampent": {
    "dex_id": 608,
    "english": "Lampent",
    "japanese": "ランプラー"
  },
  "landorus": {
    "dex_id": 645,
    "english": "Landorus",
    "japanese": "ランドロス"
  },
  "lanturn": {
    "dex_id": 171,
    "english": "Lanturn",
    "japanese": "ランターン"
  },
  "lapras": {
    "dex_id": 131,
    "english": "Lapras",
    "japanese": "ラプラス"
  },
  "larvesta": {
    "dex_id": 636,
    "english": "Larvesta",
    "japanese": "メラルバ"
  },
  "larvitar": {
    "dex_id": 246,
    "english": "Larvitar",
    "japanese": "ヨーギラス"
  },
  "latias": {
    "dex_id": 380,
    "english": "Latias",
    "japanese": "ラティアス"
  },
  "latios": {
    "dex_id": 381,
    "english": "Latios",
    "japanese": "ラティオス"
  },
  "leafeon": {
    "dex_id": 470,
    "english": "Leafeon",
    "japanese": "リーフィア"
  },
  "leavanny": {
    "dex_id": 542,
    "english": "Leavanny",
    "japanese": "ハハコモリ"
  },
  "lechonk": {
    "dex_id": 915,
    "english": "Lechonk",
    "japanese": "グルトン"
  },
  "ledian": {
    "dex_id": 166,
    "english": "Ledian",
    "japanese": "レディアン"
  },
  "ledyba": {
    "dex_id": 165,
    "english": "Ledyba",
    "japanese": "レディバ"
  },
  "lickilicky": {
    "dex_id": 463,
    "english": "Lickilicky",
    "japanese": "ベロベルト"
  },
  "lickitung": {
    "dex_id": 108,
    "english": "Lickitung",
    "japanese": "ベロリンガ"
  },
  "liepard": {
    "dex_id": 510,
    "english": "Liepard",
    "japanese": "レパルダス"
  },
  "lileep": {
    "dex_id": 345,
    "english": "Lileep",
    "japanese": "リリーラ"
  },
  "lilligant": {
    "dex_id": 549,
    "english": "Lilligant",
    "japanese": "ドレディア"
  },
  "lillipup": {
    "dex_id": 506,
    "english": "Lillipup",
    "japanese": "ヨーテリー"
  },
  "linoone": {
    "dex_id": 264,
    "english": "Linoone",
    "japanese": "マッスグマ"
  },
  "litleo": {
    "dex_id": 667,
    "english": "Litleo",
    "japanese": "シシコ"
  },
  "litten": {
    "dex_id": 725,
    "english": "Litten",
    "japanese": "ニャビー"
  },
  "litwick": {
    "dex_id": 607,
    "english": "Litwick",
    "japanese": "ヒトモシ"
  },
  "lokix": {
    "dex_id": 920,
    "english": "Lokix",
    "japanese": "エクスレッグ"
  },
  "lombre": {
    "dex_id": 271,
    "english": "Lombre",
    "japanese": "ハスブレロ"
  },
  "lopunny": {
    "dex_id": 428,
    "english": "Lopunny",
    "japanese": "ミミロップ"
  },
  "lotad": {
    "dex_id": 270,
    "english": "Lotad",
    "japanese": "ハスボー"
  },
  "loudred": {
    "dex_id": 294,
    "english": "Loudred",
    "japanese": "ドゴーム"
  },
  "lucario": {
    "dex_id": 448,
    "english": "Lucario",
    "japanese": "ルカリオ"
  },
  "ludicolo": {
    "dex_id": 272,
    "english": "Ludicolo",
    "japanese": "ルンパッパ"
  },
  "lugia": {
    "dex_id": 249,
    "english": "Lugia",
    "japanese": "ルギア"
  },
  "lumineon": {
    "dex_id": 457,
    "english": "Lumineon",
    "japanese": "ネオラント"
  },
  "lunala": {
    "dex_id": 792,
    "english": "Lunala",
    "japanese": "ルナアーラ"
  },
  "lunatone": {
    "dex_id": 337,
    "english": "Lunatone",
    "japanese": "ルナトーン"
  },
  "lurantis": {
    "dex_id": 754,
    "english": "Lurantis",
    "japanese": "ラランテス"
  },
  "luvdisc": {
    "dex_id": 370,
    "english": "Luvdisc",
    "japanese": "ラブカス"
  },
  "luxio": {
    "dex_id": 404,
    "english": "Luxio",
    "japanese": "ルクシオ"
  },
  "luxray": {
    "dex_id": 405,
    "english": "Luxray",
    "japanese": "レントラー"
  },
  "lycanroc": {
    "dex_id": 745,
    "english": "Lycanroc",
    "japanese": "ルガルガン"
  },
  "mabosstiff": {
    "dex_id": 943,
    "english": "Mabosstiff",
    "japanese": "マフィティフ"
  },
  "machamp": {
    "dex_id": 68,
    "english": "Machamp",
    "japanese": "カイリキー"
  },
  "machoke": {
    "dex_id": 67,
    "english": "Machoke",
    "japanese": "ゴーリキー"
  },
  "machop": {
    "dex_id": 66,
    "english": "Machop",
    "japanese": "ワンリキー"
  },
  "magby": {
    "dex_id": 240,
    "english": "Magby",
    "japanese": "ブビィ"
  },
  "magcargo": {
    "dex_id": 219,
    "english": "Magcargo",
    "japanese": "マグカルゴ"
  },
  "magearna": {
    "dex_id": 801,
    "english": "Magearna",
    "japanese": "マギアナ"
  },
  "magikarp": {
    "dex_id": 129,
    "english": "Magikarp",
    "japanese": "コイキング"
  },
  "magmar": {
    "dex_id": 126,
    "english": "Magmar",
    "japanese": "ブーバー"
  },
  "magmortar": {
    "dex_id": 467,
    "english": "Magmortar",
    "japanese": "ブーバーン"
  },
  "magnemite": {
    "dex_id": 81,
    "english": "Magnemite",
    "japanese": "コイル"
  },
  "magneton": {
    "dex_id": 82,
    "english": "Magneton",
    "japanese": "レアコイル"
  },
  "magnezone": {
    "dex_id": 462,
    "english": "Magnezone",
    "japanese": "ジバコイル"
  },
  "makuhita": {
    "dex_id": 296,
    "english": "Makuhita",
    "japanese": "マクノシタ"
  },
  "malamar": {
    "dex_id": 687,
    "english": "Malamar",
    "japanese": "カラマネロ"
  },
  "mamoswine": {
    "dex_id": 473,
    "english": "Mamoswine",
    "japanese": "マンムー"
  },
  "manaphy": {
    "dex_id": 490,
    "english": "Manaphy",
    "japanese": "マナフィ"
  },
  "mandibuzz": {
    "dex_id": 630,
    "english": "Mandibuzz",
    "japanese": "バルジーナ"
  },
  "manectric": {
    "dex_id": 310,
    "english": "Manectric",
    "japanese": "ライボルト"
  },
  "mankey": {
    "dex_id": 56,
    "english": "Mankey",
    "japanese": "マンキー"
  },
  "mantine": {
    "dex_id": 226,
    "english": "Mantine",
    "japanese": "マンタイン"
  },
  "mantyke": {
    "dex_id": 458,
    "english": "Mantyke",
    "japanese": "タマンタ"
  },
  "maractus": {
    "dex_id": 556,
    "english": "Maractus",
    "japanese": "マラカッチ"
  },
  "mareanie": {
    "dex_id": 747,
    "english": "Mareanie",
    "japanese": "ヒドイデ"
  },
  "mareep": {
    "dex_id": 179,
    "english": "Mareep",
    "japanese": "メリープ"
  },
  "marill": {
    "dex_id": 183,
    "english": "Marill",
    "japanese": "マリル"
  },
  "marowak": {
    "dex_id": 105,
    "english": "Marowak",
    "japanese": "ガラガラ"
  },
  "marshadow": {
    "dex_id": 802,
    "english": "Marshadow",
    "japanese": "マーシャドー"
  },
  "marshtomp": {
    "dex_id": 259,
    "english": "Marshtomp",
    "japanese": "ヌマクロー"
  },
  "maschiff": {
    "dex_id": 942,
    "english": "Maschiff",
    "japanese": "オラチフ"
  },
  "masquerain": {
    "dex_id": 284,
    "english": "Masquerain",
    "japanese": "アメモース"
  },
  "maushold": {
    "dex_id": 925,
    "english": "Maushold",
    "japanese": "イッカネズミ"
  },
  "mawile": {
    "dex_id": 303,
    "english": "Mawile",
    "japanese": "クチート"
  },
  "medicham": {
    "dex_id": 308,
    "english": "Medicham",
    "japanese": "チャーレム"
  },
  "meditite": {
    "dex_id": 307,
    "english": "Meditite",
    "japanese": "アサナン"
  },
  "meganium": {
    "dex_id": 154,
    "english": "Meganium",
    "japanese": "メガニウム"
  },
  "melmetal": {
    "dex_id": 809,
    "english": "Melmetal",
    "japanese": "メルメタル"
  },
  "meloetta": {
    "dex_id": 648,
    "english": "Meloetta",
    "japanese": "メロエッタ"
  },
  "meltan": {
    "dex_id": 808,
    "english": "Meltan",
    "japanese": "メルタン"
  },
  "meowscarada": {
    "dex_id": 908,
    "english": "Meowscarada",
    "japanese": "マスカーニャ"
  },
  "meowstic": {
    "dex_id": 678,
    "english": "Meowstic",
    "japanese": "ニャオニクス"
  },
  "meowth": {
    "dex_id": 52,
    "english": "Meowth",
    "japanese": "ニャース"
  },
  "mesprit": {
    "dex_id": 481,
    "english": "Mesprit",
    "japanese": "エムリット"
  },
  "metagross": {
    "dex_id": 376,
    "english": "Metagross",
    "japanese": "メタグロス"
  },
  "metang": {
    "dex_id": 375,
    "english": "Metang",
    "japanese": "メタング"
  },
  "metapod": {
    "dex_id": 11,
    "english": "Metapod",
    "japanese": "トランセル"
  },
  "mew": {
    "dex_id": 151,
    "english": "Mew",
    "japanese": "ミュウ"
  },
  "mewtwo": {
    "dex_id": 150,
    "english": "Mewtwo",
    "japanese": "ミュウツー"
  },
  "mienfoo": {
    "dex_id": 619,
    "english": "Mienfoo",
    "japanese": "コジョフー"
  },
  "mienshao": {
    "dex_id": 620,
    "english": "Mienshao",
    "japanese": "コジョンド"
  },
  "mightyena": {
    "dex_id": 262,
    "english": "Mightyena",
    "japanese": "グラエナ"
  },
  "milcery": {
    "dex_id": 868,
    "english": "Milcery",
    "japanese": "マホミル"
  },
  "milotic": {
    "dex_id": 350,
    "english": "Milotic",
    "japanese": "ミロカロス"
  },
  "miltank": {
    "dex_id": 241,
    "english": "Miltank",
    "japanese": "ミルタンク"
  },
  "mime jr": {
    "dex_id": 439,
    "english": "Mime Jr.",
    "japanese": "マネネ"
  },
  "mimejr": {
    "dex_id": 439,
    "english": "Mime Jr.",
    "japanese": "マネネ"
  },
  "mimikyu": {
    "dex_id": 778,
    "english": "Mimikyu",
    "japanese": "ミミッキュ"
  },
  "minccino": {
    "dex_id": 572,
    "english": "Minccino",
    "japanese": "チラーミィ"
  },
  "minior": {
    "dex_id": 774,
    "english": "Minior",
    "japanese": "メテノ"
  },
  "minun": {
    "dex_id": 312,
    "english": "Minun",
    "japanese": "マイナン"
  },
  "miraidon": {
    "dex_id": 1008,
    "english": "Miraidon",
    "japanese": "ミライドン"
  },
  "misdreavus": {
    "dex_id": 200,
    "english": "Misdreavus",
    "japanese": "ムウマ"
  },
  "mismagius": {
    "dex_id": 429,
    "english": "Mismagius",
    "japanese": "ムウマージ"
  },
  "moltres": {
    "dex_id": 146,
    "english": "Moltres",
    "japanese": "ファイヤー"
  },
  "monferno": {
    "dex_id": 391,
    "english": "Monferno",
    "japanese": "モウカザル"
  },
  "morelull": {
    "dex_id": 755,
    "english": "Morelull",
    "japanese": "ネマシュ"
  },
  "morgrem": {
    "dex_id": 860,
    "english": "Morgrem",
    "japanese": "ギモー"
  },
  "morpeko": {
    "dex_id": 877,
    "english": "Morpeko",
    "japanese": "モルペコ"
  },
  "mothim": {
    "dex_id": 414,
    "english": "Mothim",
    "japanese": "ガーメイル"
  },
  "mr mime": {
    "dex_id": 122,
    "english": "Mr. Mime",
    "japanese": "バリヤード"
  },
  "mr rime": {
    "dex_id": 866,
    "english": "Mr. Rime",
    "japanese": "バリコオル"
  },
  "mrmime": {
    "dex_id": 122,
    "english": "Mr. Mime",
    "japanese": "バリヤード"
  },
  "mrrime": {
    "dex_id": 866,
    "english": "Mr. Rime",
    "japanese": "バリコオル"
  },
  "mudbray": {
    "dex_id": 749,
    "english": "Mudbray",
    "japanese": "ドロバンコ"
  },
  "mudkip": {
    "dex_id": 258,
    "english": "Mudkip",
    "japanese": "ミズゴロウ"
  },
  "mudsdale": {
    "dex_id": 750,
    "english": "Mudsdale",
    "japanese": "バンバドロ"
  },
  "muk": {
    "dex_id": 89,
    "english": "Muk",
    "japanese": "ベトベトン"
  },
  "munchlax": {
    "dex_id": 446,
    "english": "Munchlax",
    "japanese": "ゴンベ"
  },
  "munkidori": {
    "dex_id": 1015,
    "english": "Munkidori",
    "japanese": "マシマシラ"
  },
  "munna": {
    "dex_id": 517,
    "english": "Munna",
    "japanese": "ムンナ"
  },
  "murkrow": {
    "dex_id": 198,
    "english": "Murkrow",
    "japanese": "ヤミカラス"
  },
  "musharna": {
    "dex_id": 518,
    "english": "Musharna",
    "japanese": "ムシャーナ"
  },
  "nacli": {
    "dex_id": 932,
    "english": "Nacli",
    "japanese": "コジオ"
  },
  "naclstack": {
    "dex_id": 933,
    "english": "Naclstack",
    "japanese": "ジオヅム"
  },
  "naganadel": {
    "dex_id": 804,
    "english": "Naganadel",
    "japanese": "アーゴヨン"
  },
  "natu": {
    "dex_id": 177,
    "english": "Natu",
    "japanese": "ネイティ"
  },
  "necrozma": {
    "dex_id": 800,
    "english": "Necrozma",
    "japanese": "ネクロズマ"
  },
  "nickit": {
    "dex_id": 827,
    "english": "Nickit",
    "japanese": "クスネ"
  },
  "nidoking": {
    "dex_id": 34,
    "english": "Nidoking",
    "japanese": "ニドキング"
  },
  "nidoqueen": {
    "dex_id": 31,
    "english": "Nidoqueen",
    "japanese": "ニドクイン"
  },
  "nidoran f": {
    "dex_id": 29,
    "english": "Nidoran♀",
    "japanese": "ニドラン♀"
  },
  "nidoran female": {
    "dex_id": 29,
    "english": "Nidoran♀",
    "japanese": "ニドラン♀"
  },
  "nidoran m": {
    "dex_id": 32,
    "english": "Nidoran♂",
    "japanese": "ニドラン♂"
  },
  "nidoran male": {
    "dex_id": 32,
    "english": "Nidoran♂",
    "japanese": "ニドラン♂"
  },
  "nidoranf": {
    "dex_id": 29,
    "english": "Nidoran♀",
    "japanese": "ニドラン♀"
  },
  "nidoranm": {
    "dex_id": 32,
    "english": "Nidoran♂",
    "japanese": "ニドラン♂"
  },
  "nidorina": {
    "dex_id": 30,
    "english": "Nidorina",
    "japanese": "ニドリーナ"
  },
  "nidorino": {
    "dex_id": 33,
    "english": "Nidorino",
    "japanese": "ニドリーノ"
  },
  "nihilego": {
    "dex_id": 793,
    "english": "Nihilego",
    "japanese": "ウツロイド"
  },
  "nincada": {
    "dex_id": 290,
    "english": "Nincada",
    "japanese": "ツチニン"
  },
  "ninetales": {
    "dex_id": 38,
    "english": "Ninetales",
    "japanese": "キュウコン"
  },
  "ninjask": {
    "dex_id": 291,
    "english": "Ninjask",
    "japanese": "テッカニン"
  },
  "noctowl": {
    "dex_id": 164,
    "english": "Noctowl",
    "japanese": "ヨルノズク"
  },
  "noibat": {
    "dex_id": 714,
    "english": "Noibat",
    "japanese": "オンバット"
  },
  "noivern": {
    "dex_id": 715,
    "english": "Noivern",
    "japanese": "オンバーン"
  },
  "nosepass": {
    "dex_id": 299,
    "english": "Nosepass",
    "japanese": "ノズパス"
  },
  "numel": {
    "dex_id": 322,
    "english": "Numel",
    "japanese": "ドンメル"
  },
  "nuzleaf": {
    "dex_id": 274,
    "english": "Nuzleaf",
    "japanese": "コノハナ"
  },
  "nymble": {
    "dex_id": 919,
    "english": "Nymble",
    "japanese": "マメバッタ"
  },
  "obstagoon": {
    "dex_id": 862,
    "english": "Obstagoon",
    "japanese": "タチフサグマ"
  },
  "octillery": {
    "dex_id": 224,
    "english": "Octillery",
    "japanese": "オクタン"
  },
  "oddish": {
    "dex_id": 43,
    "english": "Oddish",
    "japanese": "ナゾノクサ"
  },
  "ogerpon": {
    "dex_id": 1017,
    "english": "Ogerpon",
    "japanese": "オーガポン"
  },
  "oinkologne": {
    "dex_id": 916,
    "english": "Oinkologne",
    "japanese": "パフュートン"
  },
  "okidogi": {
    "dex_id": 1014,
    "english": "Okidogi",
    "japanese": "イイネイヌ"
  },
  "omanyte": {
    "dex_id": 138,
    "english": "Omanyte",
    "japanese": "オムナイト"
  },
  "omastar": {
    "dex_id": 139,
    "english": "Omastar",
    "japanese": "オムスター"
  },
  "onix": {
    "dex_id": 95,
    "english": "Onix",
    "japanese": "イワーク"
  },
  "oranguru": {
    "dex_id": 765,
    "english": "Oranguru",
    "japanese": "ヤレユータン"
  },
  "orbeetle": {
    "dex_id": 826,
    "english": "Orbeetle",
    "japanese": "イオルブ"
  },
  "oricorio": {
    "dex_id": 741,
    "english": "Oricorio",
    "japanese": "オドリドリ"
  },
  "orthworm": {
    "dex_id": 968,
    "english": "Orthworm",
    "japanese": "ミミズズ"
  },
  "oshawott": {
    "dex_id": 501,
    "english": "Oshawott",
    "japanese": "ミジュマル"
  },
  "overqwil": {
    "dex_id": 904,
    "english": "Overqwil",
    "japanese": "ハリーマン"
  },
  "pachirisu": {
    "dex_id": 417,
    "english": "Pachirisu",
    "japanese": "パチリス"
  },
  "palafin": {
    "dex_id": 964,
    "english": "Palafin",
    "japanese": "イルカマン"
  },
  "palkia": {
    "dex_id": 484,
    "english": "Palkia",
    "japanese": "パルキア"
  },
  "palossand": {
    "dex_id": 770,
    "english": "Palossand",
    "japanese": "シロデスナ"
  },
  "palpitoad": {
    "dex_id": 536,
    "english": "Palpitoad",
    "japanese": "ガマガル"
  },
  "pancham": {
    "dex_id": 674,
    "english": "Pancham",
    "japanese": "ヤンチャム"
  },
  "pangoro": {
    "dex_id": 675,
    "english": "Pangoro",
    "japanese": "ゴロンダ"
  },
  "panpour": {
    "dex_id": 515,
    "english": "Panpour",
    "japanese": "ヒヤップ"
  },
  "pansage": {
    "dex_id": 511,
    "english": "Pansage",
    "japanese": "ヤナップ"
  },
  "pansear": {
    "dex_id": 513,
    "english": "Pansear",
    "japanese": "バオップ"
  },
  "paras": {
    "dex_id": 46,
    "english": "Paras",
    "japanese": "パラス"
  },
  "parasect": {
    "dex_id": 47,
    "english": "Parasect",
    "japanese": "パラセクト"
  },
  "passimian": {
    "dex_id": 766,
    "english": "Passimian",
    "japanese": "ナゲツケサル"
  },
  "patrat": {
    "dex_id": 504,
    "english": "Patrat",
    "japanese": "ミネズミ"
  },
  "pawmi": {
    "dex_id": 921,
    "english": "Pawmi",
    "japanese": "パモ"
  },
  "pawmo": {
    "dex_id": 922,
    "english": "Pawmo",
    "japanese": "パモット"
  },
  "pawmot": {
    "dex_id": 923,
    "english": "Pawmot",
    "japanese": "パーモット"
  },
  "pawniard": {
    "dex_id": 624,
    "english": "Pawniard",
    "japanese": "コマタナ"
  },
  "pecharunt": {
    "dex_id": 1025,
    "english": "Pecharunt",
    "japanese": "モモワロウ"
  },
  "pelipper": {
    "dex_id": 279,
    "english": "Pelipper",
    "japanese": "ペリッパー"
  },
  "perrserker": {
    "dex_id": 863,
    "english": "Perrserker",
    "japanese": "ニャイキング"
  },
  "persian": {
    "dex_id": 53,
    "english": "Persian",
    "japanese": "ペルシアン"
  },
  "petilil": {
    "dex_id": 548,
    "english": "Petilil",
    "japanese": "チュリネ"
  },
  "phanpy": {
    "dex_id": 231,
    "english": "Phanpy",
    "japanese": "ゴマゾウ"
  },
  "phantump": {
    "dex_id": 708,
    "english": "Phantump",
    "japanese": "ボクレー"
  },
  "pheromosa": {
    "dex_id": 795,
    "english": "Pheromosa",
    "japanese": "フェローチェ"
  },
  "phione": {
    "dex_id": 489,
    "english": "Phione",
    "japanese": "フィオネ"
  },
  "pichu": {
    "dex_id": 172,
    "english": "Pichu",
    "japanese": "ピチュー"
  },
  "pidgeot": {
    "dex_id": 18,
    "english": "Pidgeot",
    "japanese": "ピジョット"
  },
  "pidgeotto": {
    "dex_id": 17,
    "english": "Pidgeotto",
    "japanese": "ピジョン"
  },
  "pidgey": {
    "dex_id": 16,
    "english": "Pidgey",
    "japanese": "ポッポ"
  },
  "pidove": {
    "dex_id": 519,
    "english": "Pidove",
    "japanese": "マメパト"
  },
  "pignite": {
    "dex_id": 499,
    "english": "Pignite",
    "japanese": "チャオブー"
  },
  "pikachu": {
    "dex_id": 25,
    "english": "Pikachu",
    "japanese": "ピカチュウ"
  },
  "pikipek": {
    "dex_id": 731,
    "english": "Pikipek",
    "japanese": "ツツケラ"
  },
  "piloswine": {
    "dex_id": 221,
    "english": "Piloswine",
    "japanese": "イノムー"
  },
  "pincurchin": {
    "dex_id": 871,
    "english": "Pincurchin",
    "japanese": "バチンウニ"
  },
  "pineco": {
    "dex_id": 204,
    "english": "Pineco",
    "japanese": "クヌギダマ"
  },
  "pinsir": {
    "dex_id": 127,
    "english": "Pinsir",
    "japanese": "カイロス"
  },
  "piplup": {
    "dex_id": 393,
    "english": "Piplup",
    "japanese": "ポッチャマ"
  },
  "plusle": {
    "dex_id": 311,
    "english": "Plusle",
    "japanese": "プラスル"
  },
  "poipole": {
    "dex_id": 803,
    "english": "Poipole",
    "japanese": "ベベノム"
  },
  "politoed": {
    "dex_id": 186,
    "english": "Politoed",
    "japanese": "ニョロトノ"
  },
  "poliwag": {
    "dex_id": 60,
    "english": "Poliwag",
    "japanese": "ニョロモ"
  },
  "poliwhirl": {
    "dex_id": 61,
    "english": "Poliwhirl",
    "japanese": "ニョロゾ"
  },
  "poliwrath": {
    "dex_id": 62,
    "english": "Poliwrath",
    "japanese": "ニョロボン"
  },
  "poltchageist": {
    "dex_id": 1012,
    "english": "Poltchageist",
    "japanese": "チャデス"
  },
  "polteageist": {
    "dex_id": 855,
    "english": "Polteageist",
    "japanese": "ポットデス"
  },
  "ponyta": {
    "dex_id": 77,
    "english": "Ponyta",
    "japanese": "ポニータ"
  },
  "poochyena": {
    "dex_id": 261,
    "english": "Poochyena",
    "japanese": "ポチエナ"
  },
  "popplio": {
    "dex_id": 728,
    "english": "Popplio",
    "japanese": "アシマリ"
  },
  "porygon": {
    "dex_id": 137,
    "english": "Porygon",
    "japanese": "ポリゴン"
  },
  "porygon z": {
    "dex_id": 474,
    "english": "Porygon-Z",
    "japanese": "ポリゴンＺ"
  },
  "porygon2": {
    "dex_id": 233,
    "english": "Porygon2",
    "japanese": "ポリゴン２"
  },
  "porygonz": {
    "dex_id": 474,
    "english": "Porygon-Z",
    "japanese": "ポリゴンＺ"
  },
  "primarina": {
    "dex_id": 730,
    "english": "Primarina",
    "japanese": "アシレーヌ"
  },
  "primeape": {
    "dex_id": 57,
    "english": "Primeape",
    "japanese": "オコリザル"
  },
  "prinplup": {
    "dex_id": 394,
    "english": "Prinplup",
    "japanese": "ポッタイシ"
  },
  "probopass": {
    "dex_id": 476,
    "english": "Probopass",
    "japanese": "ダイノーズ"
  },
  "psyduck": {
    "dex_id": 54,
    "english": "Psyduck",
    "japanese": "コダック"
  },
  "pumpkaboo": {
    "dex_id": 710,
    "english": "Pumpkaboo",
    "japanese": "バケッチャ"
  },
  "pupitar": {
    "dex_id": 247,
    "english": "Pupitar",
    "japanese": "サナギラス"
  },
  "purrloin": {
    "dex_id": 509,
    "english": "Purrloin",
    "japanese": "チョロネコ"
  },
  "purugly": {
    "dex_id": 432,
    "english": "Purugly",
    "japanese": "ブニャット"
  },
  "pyroar": {
    "dex_id": 668,
    "english": "Pyroar",
    "japanese": "カエンジシ"
  },
  "pyukumuku": {
    "dex_id": 771,
    "english": "Pyukumuku",
    "japanese": "ナマコブシ"
  },
  "quagsire": {
    "dex_id": 195,
    "english": "Quagsire",
    "japanese": "ヌオー"
  },
  "quaquaval": {
    "dex_id": 914,
    "english": "Quaquaval",
    "japanese": "ウェーニバル"
  },
  "quaxly": {
    "dex_id": 912,
    "english": "Quaxly",
    "japanese": "クワッス"
  },
  "quaxwell": {
    "dex_id": 913,
    "english": "Quaxwell",
    "japanese": "ウェルカモ"
  },
  "quilava": {
    "dex_id": 156,
    "english": "Quilava",
    "japanese": "マグマラシ"
  },
  "quilladin": {
    "dex_id": 651,
    "english": "Quilladin",
    "japanese": "ハリボーグ"
  },
  "qwilfish": {
    "dex_id": 211,
    "english": "Qwilfish",
    "japanese": "ハリーセン"
  },
  "raboot": {
    "dex_id": 814,
    "english": "Raboot",
    "japanese": "ラビフット"
  },
  "rabsca": {
    "dex_id": 954,
    "english": "Rabsca",
    "japanese": "ベラカス"
  },
  "raging bolt": {
    "dex_id": 1021,
    "english": "Raging Bolt",
    "japanese": "タケルライコ"
  },
  "ragingbolt": {
    "dex_id": 1021,
    "english": "Raging Bolt",
    "japanese": "タケルライコ"
  },
  "raichu": {
    "dex_id": 26,
    "english": "Raichu",
    "japanese": "ライチュウ"
  },
  "raikou": {
    "dex_id": 243,
    "english": "Raikou",
    "japanese": "ライコウ"
  },
  "ralts": {
    "dex_id": 280,
    "english": "Ralts",
    "japanese": "ラルトス"
  },
  "rampardos": {
    "dex_id": 409,
    "english": "Rampardos",
    "japanese": "ラムパルド"
  },
  "rapidash": {
    "dex_id": 78,
    "english": "Rapidash",
    "japanese": "ギャロップ"
  },
  "raticate": {
    "dex_id": 20,
    "english": "Raticate",
    "japanese": "ラッタ"
  },
  "rattata": {
    "dex_id": 19,
    "english": "Rattata",
    "japanese": "コラッタ"
  },
  "rayquaza": {
    "dex_id": 384,
    "english": "Rayquaza",
    "japanese": "レックウザ"
  },
  "regice": {
    "dex_id": 378,
    "english": "Regice",
    "japanese": "レジアイス"
  },
  "regidrago": {
    "dex_id": 895,
    "english": "Regidrago",
    "japanese": "レジドラゴ"
  },
  "regieleki": {
    "dex_id": 894,
    "english": "Regieleki",
    "japanese": "レジエレキ"
  },
  "regigigas": {
    "dex_id": 486,
    "english": "Regigigas",
    "japanese": "レジギガス"
  },
  "regirock": {
    "dex_id": 377,
    "english": "Regirock",
    "japanese": "レジロック"
  },
  "registeel": {
    "dex_id": 379,
    "english": "Registeel",
    "japanese": "レジスチル"
  },
  "relicanth": {
    "dex_id": 369,
    "english": "Relicanth",
    "japanese": "ジーランス"
  },
  "rellor": {
    "dex_id": 953,
    "english": "Rellor",
    "japanese": "シガロコ"
  },
  "remoraid": {
    "dex_id": 223,
    "english": "Remoraid",
    "japanese": "テッポウオ"
  },
  "reshiram": {
    "dex_id": 643,
    "english": "Reshiram",
    "japanese": "レシラム"
  },
  "reuniclus": {
    "dex_id": 579,
    "english": "Reuniclus",
    "japanese": "ランクルス"
  },
  "revavroom": {
    "dex_id": 966,
    "english": "Revavroom",
    "japanese": "ブロロローム"
  },
  "rhydon": {
    "dex_id": 112,
    "english": "Rhydon",
    "japanese": "サイドン"
  },
  "rhyhorn": {
    "dex_id": 111,
    "english": "Rhyhorn",
    "japanese": "サイホーン"
  },
  "rhyperior": {
    "dex_id": 464,
    "english": "Rhyperior",
    "japanese": "ドサイドン"
  },
  "ribombee": {
    "dex_id": 743,
    "english": "Ribombee",
    "japanese": "アブリボン"
  },
  "rillaboom": {
    "dex_id": 812,
    "english": "Rillaboom",
    "japanese": "ゴリランダー"
  },
  "riolu": {
    "dex_id": 447,
    "english": "Riolu",
    "japanese": "リオル"
  },
  "roaring moon": {
    "dex_id": 1005,
    "english": "Roaring Moon",
    "japanese": "トドロクツキ"
  },
  "roaringmoon": {
    "dex_id": 1005,
    "english": "Roaring Moon",
    "japanese": "トドロクツキ"
  },
  "rockruff": {
    "dex_id": 744,
    "english": "Rockruff",
    "japanese": "イワンコ"
  },
  "roggenrola": {
    "dex_id": 524,
    "english": "Roggenrola",
    "japanese": "ダンゴロ"
  },
  "rolycoly": {
    "dex_id": 837,
    "english": "Rolycoly",
    "japanese": "タンドン"
  },
  "rookidee": {
    "dex_id": 821,
    "english": "Rookidee",
    "japanese": "ココガラ"
  },
  "roselia": {
    "dex_id": 315,
    "english": "Roselia",
    "japanese": "ロゼリア"
  },
  "roserade": {
    "dex_id": 407,
    "english": "Roserade",
    "japanese": "ロズレイド"
  },
  "rotom": {
    "dex_id": 479,
    "english": "Rotom",
    "japanese": "ロトム"
  },
  "rowlet": {
    "dex_id": 722,
    "english": "Rowlet",
    "japanese": "モクロー"
  },
  "rufflet": {
    "dex_id": 627,
    "english": "Rufflet",
    "japanese": "ワシボン"
  },
  "runerigus": {
    "dex_id": 867,
    "english": "Runerigus",
    "japanese": "デスバーン"
  },
  "sableye": {
    "dex_id": 302,
    "english": "Sableye",
    "japanese": "ヤミラミ"
  },
  "salamence": {
    "dex_id": 373,
    "english": "Salamence",
    "japanese": "ボーマンダ"
  },
  "salandit": {
    "dex_id": 757,
    "english": "Salandit",
    "japanese": "ヤトウモリ"
  },
  "salazzle": {
    "dex_id": 758,
    "english": "Salazzle",
    "japanese": "エンニュート"
  },
  "samurott": {
    "dex_id": 503,
    "english": "Samurott",
    "japanese": "ダイケンキ"
  },
  "sandaconda": {
    "dex_id": 844,
    "english": "Sandaconda",
    "japanese": "サダイジャ"
  },
  "sandile": {
    "dex_id": 551,
    "english": "Sandile",
    "japanese": "メグロコ"
  },
  "sandshrew": {
    "dex_id": 27,
    "english": "Sandshrew",
    "japanese": "サンド"
  },
  "sandslash": {
    "dex_id": 28,
    "english": "Sandslash",
    "japanese": "サンドパン"
  },
  "sandy shocks": {
    "dex_id": 989,
    "english": "Sandy Shocks",
    "japanese": "スナノケガワ"
  },
  "sandygast": {
    "dex_id": 769,
    "english": "Sandygast",
    "japanese": "スナバァ"
  },
  "sandyshocks": {
    "dex_id": 989,
    "english": "Sandy Shocks",
    "japanese": "スナノケガワ"
  },
  "sawk": {
    "dex_id": 539,
    "english": "Sawk",
    "japanese": "ダゲキ"
  },
  "sawsbuck": {
    "dex_id": 586,
    "english": "Sawsbuck",
    "japanese": "メブキジカ"
  },
  "scatterbug": {
    "dex_id": 664,
    "english": "Scatterbug",
    "japanese": "コフキムシ"
  },
  "sceptile": {
    "dex_id": 254,
    "english": "Sceptile",
    "japanese": "ジュカイン"
  },
  "scizor": {
    "dex_id": 212,
    "english": "Scizor",
    "japanese": "ハッサム"
  },
  "scolipede": {
    "dex_id": 545,
    "english": "Scolipede",
    "japanese": "ペンドラー"
  },
  "scorbunny": {
    "dex_id": 813,
    "english": "Scorbunny",
    "japanese": "ヒバニー"
  },
  "scovillain": {
    "dex_id": 952,
    "english": "Scovillain",
    "japanese": "スコヴィラン"
  },
  "scrafty": {
    "dex_id": 560,
    "english": "Scrafty",
    "japanese": "ズルズキン"
  },
  "scraggy": {
    "dex_id": 559,
    "english": "Scraggy",
    "japanese": "ズルッグ"
  },
  "scream tail": {
    "dex_id": 985,
    "english": "Scream Tail",
    "japanese": "サケブシッポ"
  },
  "screamtail": {
    "dex_id": 985,
    "english": "Scream Tail",
    "japanese": "サケブシッポ"
  },
  "scyther": {
    "dex_id": 123,
    "english": "Scyther",
    "japanese": "ストライク"
  },
  "seadra": {
    "dex_id": 117,
    "english": "Seadra",
    "japanese": "シードラ"
  },
  "seaking": {
    "dex_id": 119,
    "english": "Seaking",
    "japanese": "アズマオウ"
  },
  "sealeo": {
    "dex_id": 364,
    "english": "Sealeo",
    "japanese": "トドグラー"
  },
  "seedot": {
    "dex_id": 273,
    "english": "Seedot",
    "japanese": "タネボー"
  },
  "seel": {
    "dex_id": 86,
    "english": "Seel",
    "japanese": "パウワウ"
  },
  "seismitoad": {
    "dex_id": 537,
    "english": "Seismitoad",
    "japanese": "ガマゲロゲ"
  },
  "sentret": {
    "dex_id": 161,
    "english": "Sentret",
    "japanese": "オタチ"
  },
  "serperior": {
    "dex_id": 497,
    "english": "Serperior",
    "japanese": "ジャローダ"
  },
  "servine": {
    "dex_id": 496,
    "english": "Servine",
    "japanese": "ジャノビー"
  },
  "seviper": {
    "dex_id": 336,
    "english": "Seviper",
    "japanese": "ハブネーク"
  },
  "sewaddle": {
    "dex_id": 540,
    "english": "Sewaddle",
    "japanese": "クルミル"
  },
  "sharpedo": {
    "dex_id": 319,
    "english": "Sharpedo",
    "japanese": "サメハダー"
  },
  "shaymin": {
    "dex_id": 492,
    "english": "Shaymin",
    "japanese": "シェイミ"
  },
  "shedinja": {
    "dex_id": 292,
    "english": "Shedinja",
    "japanese": "ヌケニン"
  },
  "shelgon": {
    "dex_id": 372,
    "english": "Shelgon",
    "japanese": "コモルー"
  },
  "shellder": {
    "dex_id": 90,
    "english": "Shellder",
    "japanese": "シェルダー"
  },
  "shellos": {
    "dex_id": 422,
    "english": "Shellos",
    "japanese": "カラナクシ"
  },
  "shelmet": {
    "dex_id": 616,
    "english": "Shelmet",
    "japanese": "チョボマキ"
  },
  "shieldon": {
    "dex_id": 410,
    "english": "Shieldon",
    "japanese": "タテトプス"
  },
  "shiftry": {
    "dex_id": 275,
    "english": "Shiftry",
    "japanese": "ダーテング"
  },
  "shiinotic": {
    "dex_id": 756,
    "english": "Shiinotic",
    "japanese": "マシェード"
  },
  "shinx": {
    "dex_id": 403,
    "english": "Shinx",
    "japanese": "コリンク"
  },
  "shroodle": {
    "dex_id": 944,
    "english": "Shroodle",
    "japanese": "シルシュルー"
  },
  "shroomish": {
    "dex_id": 285,
    "english": "Shroomish",
    "japanese": "キノココ"
  },
  "shuckle": {
    "dex_id": 213,
    "english": "Shuckle",
    "japanese": "ツボツボ"
  },
  "shuppet": {
    "dex_id": 353,
    "english": "Shuppet",
    "japanese": "カゲボウズ"
  },
  "sigilyph": {
    "dex_id": 561,
    "english": "Sigilyph",
    "japanese": "シンボラー"
  },
  "silcoon": {
    "dex_id": 266,
    "english": "Silcoon",
    "japanese": "カラサリス"
  },
  "silicobra": {
    "dex_id": 843,
    "english": "Silicobra",
    "japanese": "スナヘビ"
  },
  "silvally": {
    "dex_id": 773,
    "english": "Silvally",
    "japanese": "シルヴァディ"
  },
  "simipour": {
    "dex_id": 516,
    "english": "Simipour",
    "japanese": "ヒヤッキー"
  },
  "simisage": {
    "dex_id": 512,
    "english": "Simisage",
    "japanese": "ヤナッキー"
  },
  "simisear": {
    "dex_id": 514,
    "english": "Simisear",
    "japanese": "バオッキー"
  },
  "sinistcha": {
    "dex_id": 1013,
    "english": "Sinistcha",
    "japanese": "ヤバソチャ"
  },
  "sinistea": {
    "dex_id": 854,
    "english": "Sinistea",
    "japanese": "ヤバチャ"
  },
  "sirfetch d": {
    "dex_id": 865,
    "english": "Sirfetch’d",
    "japanese": "ネギガナイト"
  },
  "sirfetchd": {
    "dex_id": 865,
    "english": "Sirfetch’d",
    "japanese": "ネギガナイト"
  },
  "sizzlipede": {
    "dex_id": 850,
    "english": "Sizzlipede",
    "japanese": "ヤクデ"
  },
  "skarmory": {
    "dex_id": 227,
    "english": "Skarmory",
    "japanese": "エアームド"
  },
  "skeledirge": {
    "dex_id": 911,
    "english": "Skeledirge",
    "japanese": "ラウドボーン"
  },
  "skiddo": {
    "dex_id": 672,
    "english": "Skiddo",
    "japanese": "メェークル"
  },
  "skiploom": {
    "dex_id": 188,
    "english": "Skiploom",
    "japanese": "ポポッコ"
  },
  "skitty": {
    "dex_id": 300,
    "english": "Skitty",
    "japanese": "エネコ"
  },
  "skorupi": {
    "dex_id": 451,
    "english": "Skorupi",
    "japanese": "スコルピ"
  },
  "skrelp": {
    "dex_id": 690,
    "english": "Skrelp",
    "japanese": "クズモー"
  },
  "skuntank": {
    "dex_id": 435,
    "english": "Skuntank",
    "japanese": "スカタンク"
  },
  "skwovet": {
    "dex_id": 819,
    "english": "Skwovet",
    "japanese": "ホシガリス"
  },
  "slaking": {
    "dex_id": 289,
    "english": "Slaking",
    "japanese": "ケッキング"
  },
  "slakoth": {
    "dex_id": 287,
    "english": "Slakoth",
    "japanese": "ナマケロ"
  },
  "sliggoo": {
    "dex_id": 705,
    "english": "Sliggoo",
    "japanese": "ヌメイル"
  },
  "slither wing": {
    "dex_id": 988,
    "english": "Slither Wing",
    "japanese": "チヲハウハネ"
  },
  "slitherwing": {
    "dex_id": 988,
    "english": "Slither Wing",
    "japanese": "チヲハウハネ"
  },
  "slowbro": {
    "dex_id": 80,
    "english": "Slowbro",
    "japanese": "ヤドラン"
  },
  "slowking": {
    "dex_id": 199,
    "english": "Slowking",
    "japanese": "ヤドキング"
  },
  "slowpoke": {
    "dex_id": 79,
    "english": "Slowpoke",
    "japanese": "ヤドン"
  },
  "slugma": {
    "dex_id": 218,
    "english": "Slugma",
    "japanese": "マグマッグ"
  },
  "slurpuff": {
    "dex_id": 685,
    "english": "Slurpuff",
    "japanese": "ペロリーム"
  },
  "smeargle": {
    "dex_id": 235,
    "english": "Smeargle",
    "japanese": "ドーブル"
  },
  "smoliv": {
    "dex_id": 928,
    "english": "Smoliv",
    "japanese": "ミニーブ"
  },
  "smoochum": {
    "dex_id": 238,
    "english": "Smoochum",
    "japanese": "ムチュール"
  },
  "sneasel": {
    "dex_id": 215,
    "english": "Sneasel",
    "japanese": "ニューラ"
  },
  "sneasler": {
    "dex_id": 903,
    "english": "Sneasler",
    "japanese": "オオニューラ"
  },
  "snivy": {
    "dex_id": 495,
    "english": "Snivy",
    "japanese": "ツタージャ"
  },
  "snom": {
    "dex_id": 872,
    "english": "Snom",
    "japanese": "ユキハミ"
  },
  "snorlax": {
    "dex_id": 143,
    "english": "Snorlax",
    "japanese": "カビゴン"
  },
  "snorunt": {
    "dex_id": 361,
    "english": "Snorunt",
    "japanese": "ユキワラシ"
  },
  "snover": {
    "dex_id": 459,
    "english": "Snover",
    "japanese": "ユキカブリ"
  },
  "snubbull": {
    "dex_id": 209,
    "english": "Snubbull",
    "japanese": "ブルー"
  },
  "sobble": {
    "dex_id": 816,
    "english": "Sobble",
    "japanese": "メッソン"
  },
  "solgaleo": {
    "dex_id": 791,
    "english": "Solgaleo",
    "japanese": "ソルガレオ"
  },
  "solosis": {
    "dex_id": 577,
    "english": "Solosis",
    "japanese": "ユニラン"
  },
  "solrock": {
    "dex_id": 338,
    "english": "Solrock",
    "japanese": "ソルロック"
  },
  "spearow": {
    "dex_id": 21,
    "english": "Spearow",
    "japanese": "オニスズメ"
  },
  "spectrier": {
    "dex_id": 897,
    "english": "Spectrier",
    "japanese": "レイスポス"
  },
  "spewpa": {
    "dex_id": 665,
    "english": "Spewpa",
    "japanese": "コフーライ"
  },
  "spheal": {
    "dex_id": 363,
    "english": "Spheal",
    "japanese": "タマザラシ"
  },
  "spidops": {
    "dex_id": 918,
    "english": "Spidops",
    "japanese": "ワナイダー"
  },
  "spinarak": {
    "dex_id": 167,
    "english": "Spinarak",
    "japanese": "イトマル"
  },
  "spinda": {
    "dex_id": 327,
    "english": "Spinda",
    "japanese": "パッチール"
  },
  "spiritomb": {
    "dex_id": 442,
    "english": "Spiritomb",
    "japanese": "ミカルゲ"
  },
  "spoink": {
    "dex_id": 325,
    "english": "Spoink",
    "japanese": "バネブー"
  },
  "sprigatito": {
    "dex_id": 906,
    "english": "Sprigatito",
    "japanese": "ニャオハ"
  },
  "spritzee": {
    "dex_id": 682,
    "english": "Spritzee",
    "japanese": "シュシュプ"
  },
  "squawkabilly": {
    "dex_id": 931,
    "english": "Squawkabilly",
    "japanese": "イキリンコ"
  },
  "squirtle": {
    "dex_id": 7,
    "english": "Squirtle",
    "japanese": "ゼニガメ"
  },
  "stakataka": {
    "dex_id": 805,
    "english": "Stakataka",
    "japanese": "ツンデツンデ"
  },
  "stantler": {
    "dex_id": 234,
    "english": "Stantler",
    "japanese": "オドシシ"
  },
  "staraptor": {
    "dex_id": 398,
    "english": "Staraptor",
    "japanese": "ムクホーク"
  },
  "staravia": {
    "dex_id": 397,
    "english": "Staravia",
    "japanese": "ムクバード"
  },
  "starly": {
    "dex_id": 396,
    "english": "Starly",
    "japanese": "ムックル"
  },
  "starmie": {
    "dex_id": 121,
    "english": "Starmie",
    "japanese": "スターミー"
  },
  "staryu": {
    "dex_id": 120,
    "english": "Staryu",
    "japanese": "ヒトデマン"
  },
  "steelix": {
    "dex_id": 208,
    "english": "Steelix",
    "japanese": "ハガネール"
  },
  "steenee": {
    "dex_id": 762,
    "english": "Steenee",
    "japanese": "アママイコ"
  },
  "stonjourner": {
    "dex_id": 874,
    "english": "Stonjourner",
    "japanese": "イシヘンジン"
  },
  "stoutland": {
    "dex_id": 508,
    "english": "Stoutland",
    "japanese": "ムーランド"
  },
  "stufful": {
    "dex_id": 759,
    "english": "Stufful",
    "japanese": "ヌイコグマ"
  },
  "stunfisk": {
    "dex_id": 618,
    "english": "Stunfisk",
    "japanese": "マッギョ"
  },
  "stunky": {
    "dex_id": 434,
    "english": "Stunky",
    "japanese": "スカンプー"
  },
  "sudowoodo": {
    "dex_id": 185,
    "english": "Sudowoodo",
    "japanese": "ウソッキー"
  },
  "suicune": {
    "dex_id": 245,
    "english": "Suicune",
    "japanese": "スイクン"
  },
  "sunflora": {
    "dex_id": 192,
    "english": "Sunflora",
    "japanese": "キマワリ"
  },
  "sunkern": {
    "dex_id": 191,
    "english": "Sunkern",
    "japanese": "ヒマナッツ"
  },
  "surskit": {
    "dex_id": 283,
    "english": "Surskit",
    "japanese": "アメタマ"
  },
  "swablu": {
    "dex_id": 333,
    "english": "Swablu",
    "japanese": "チルット"
  },
  "swadloon": {
    "dex_id": 541,
    "english": "Swadloon",
    "japanese": "クルマユ"
  },
  "swalot": {
    "dex_id": 317,
    "english": "Swalot",
    "japanese": "マルノーム"
  },
  "swampert": {
    "dex_id": 260,
    "english": "Swampert",
    "japanese": "ラグラージ"
  },
  "swanna": {
    "dex_id": 581,
    "english": "Swanna",
    "japanese": "スワンナ"
  },
  "swellow": {
    "dex_id": 277,
    "english": "Swellow",
    "japanese": "オオスバメ"
  },
  "swinub": {
    "dex_id": 220,
    "english": "Swinub",
    "japanese": "ウリムー"
  },
  "swirlix": {
    "dex_id": 684,
    "english": "Swirlix",
    "japanese": "ペロッパフ"
  },
  "swoobat": {
    "dex_id": 528,
    "english": "Swoobat",
    "japanese": "ココロモリ"
  },
  "sylveon": {
    "dex_id": 700,
    "english": "Sylveon",
    "japanese": "ニンフィア"
  },
  "tadbulb": {
    "dex_id": 938,
    "english": "Tadbulb",
    "japanese": "ズピカ"
  },
  "taillow": {
    "dex_id": 276,
    "english": "Taillow",
    "japanese": "スバメ"
  },
  "talonflame": {
    "dex_id": 663,
    "english": "Talonflame",
    "japanese": "ファイアロー"
  },
  "tandemaus": {
    "dex_id": 924,
    "english": "Tandemaus",
    "japanese": "ワッカネズミ"
  },
  "tangela": {
    "dex_id": 114,
    "english": "Tangela",
    "japanese": "モンジャラ"
  },
  "tangrowth": {
    "dex_id": 465,
    "english": "Tangrowth",
    "japanese": "モジャンボ"
  },
  "tapu bulu": {
    "dex_id": 787,
    "english": "Tapu Bulu",
    "japanese": "カプ・ブルル"
  },
  "tapu fini": {
    "dex_id": 788,
    "english": "Tapu Fini",
    "japanese": "カプ・レヒレ"
  },
  "tapu koko": {
    "dex_id": 785,
    "english": "Tapu Koko",
    "japanese": "カプ・コケコ"
  },
  "tapu lele": {
    "dex_id": 786,
    "english": "Tapu Lele",
    "japanese": "カプ・テテフ"
  },
  "tapubulu": {
    "dex_id": 787,
    "english": "Tapu Bulu",
    "japanese": "カプ・ブルル"
  },
  "tapufini": {
    "dex_id": 788,
    "english": "Tapu Fini",
    "japanese": "カプ・レヒレ"
  },
  "tapukoko": {
    "dex_id": 785,
    "english": "Tapu Koko",
    "japanese": "カプ・コケコ"
  },
  "tapulele": {
    "dex_id": 786,
    "english": "Tapu Lele",
    "japanese": "カプ・テテフ"
  },
  "tarountula": {
    "dex_id": 917,
    "english": "Tarountula",
    "japanese": "タマンチュラ"
  },
  "tatsugiri": {
    "dex_id": 978,
    "english": "Tatsugiri",
    "japanese": "シャリタツ"
  },
  "tauros": {
    "dex_id": 128,
    "english": "Tauros",
    "japanese": "ケンタロス"
  },
  "teddiursa": {
    "dex_id": 216,
    "english": "Teddiursa",
    "japanese": "ヒメグマ"
  },
  "tentacool": {
    "dex_id": 72,
    "english": "Tentacool",
    "japanese": "メノクラゲ"
  },
  "tentacruel": {
    "dex_id": 73,
    "english": "Tentacruel",
    "japanese": "ドククラゲ"
  },
  "tepig": {
    "dex_id": 498,
    "english": "Tepig",
    "japanese": "ポカブ"
  },
  "terapagos": {
    "dex_id": 1024,
    "english": "Terapagos",
    "japanese": "テラパゴス"
  },
  "terrakion": {
    "dex_id": 639,
    "english": "Terrakion",
    "japanese": "テラキオン"
  },
  "thievul": {
    "dex_id": 828,
    "english": "Thievul",
    "japanese": "フォクスライ"
  },
  "throh": {
    "dex_id": 538,
    "english": "Throh",
    "japanese": "ナゲキ"
  },
  "thundurus": {
    "dex_id": 642,
    "english": "Thundurus",
    "japanese": "ボルトロス"
  },
  "thwackey": {
    "dex_id": 811,
    "english": "Thwackey",
    "japanese": "バチンキー"
  },
  "timburr": {
    "dex_id": 532,
    "english": "Timburr",
    "japanese": "ドッコラー"
  },
  "ting lu": {
    "dex_id": 1003,
    "english": "Ting-Lu",
    "japanese": "ディンルー"
  },
  "tinglu": {
    "dex_id": 1003,
    "english": "Ting-Lu",
    "japanese": "ディンルー"
  },
  "tinkatink": {
    "dex_id": 957,
    "english": "Tinkatink",
    "japanese": "カヌチャン"
  },
  "tinkaton": {
    "dex_id": 959,
    "english": "Tinkaton",
    "japanese": "デカヌチャン"
  },
  "tinkatuff": {
    "dex_id": 958,
    "english": "Tinkatuff",
    "japanese": "ナカヌチャン"
  },
  "tirtouga": {
    "dex_id": 564,
    "english": "Tirtouga",
    "japanese": "プロトーガ"
  },
  "toedscool": {
    "dex_id": 948,
    "english": "Toedscool",
    "japanese": "ノノクラゲ"
  },
  "toedscruel": {
    "dex_id": 949,
    "english": "Toedscruel",
    "japanese": "リククラゲ"
  },
  "togedemaru": {
    "dex_id": 777,
    "english": "Togedemaru",
    "japanese": "トゲデマル"
  },
  "togekiss": {
    "dex_id": 468,
    "english": "Togekiss",
    "japanese": "トゲキッス"
  },
  "togepi": {
    "dex_id": 175,
    "english": "Togepi",
    "japanese": "トゲピー"
  },
  "togetic": {
    "dex_id": 176,
    "english": "Togetic",
    "japanese": "トゲチック"
  },
  "torchic": {
    "dex_id": 255,
    "english": "Torchic",
    "japanese": "アチャモ"
  },
  "torkoal": {
    "dex_id": 324,
    "english": "Torkoal",
    "japanese": "コータス"
  },
  "tornadus": {
    "dex_id": 641,
    "english": "Tornadus",
    "japanese": "トルネロス"
  },
  "torracat": {
    "dex_id": 726,
    "english": "Torracat",
    "japanese": "ニャヒート"
  },
  "torterra": {
    "dex_id": 389,
    "english": "Torterra",
    "japanese": "ドダイトス"
  },
  "totodile": {
    "dex_id": 158,
    "english": "Totodile",
    "japanese": "ワニノコ"
  },
  "toucannon": {
    "dex_id": 733,
    "english": "Toucannon",
    "japanese": "ドデカバシ"
  },
  "toxapex": {
    "dex_id": 748,
    "english": "Toxapex",
    "japanese": "ドヒドイデ"
  },
  "toxel": {
    "dex_id": 848,
    "english": "Toxel",
    "japanese": "エレズン"
  },
  "toxicroak": {
    "dex_id": 454,
    "english": "Toxicroak",
    "japanese": "ドクロッグ"
  },
  "toxtricity": {
    "dex_id": 849,
    "english": "Toxtricity",
    "japanese": "ストリンダー"
  },
  "tranquill": {
    "dex_id": 520,
    "english": "Tranquill",
    "japanese": "ハトーボー"
  },
  "trapinch": {
    "dex_id": 328,
    "english": "Trapinch",
    "japanese": "ナックラー"
  },
  "treecko": {
    "dex_id": 252,
    "english": "Treecko",
    "japanese": "キモリ"
  },
  "trevenant": {
    "dex_id": 709,
    "english": "Trevenant",
    "japanese": "オーロット"
  },
  "tropius": {
    "dex_id": 357,
    "english": "Tropius",
    "japanese": "トロピウス"
  },
  "trubbish": {
    "dex_id": 568,
    "english": "Trubbish",
    "japanese": "ヤブクロン"
  },
  "trumbeak": {
    "dex_id": 732,
    "english": "Trumbeak",
    "japanese": "ケララッパ"
  },
  "tsareena": {
    "dex_id": 763,
    "english": "Tsareena",
    "japanese": "アマージョ"
  },
  "turtonator": {
    "dex_id": 776,
    "english": "Turtonator",
    "japanese": "バクガメス"
  },
  "turtwig": {
    "dex_id": 387,
    "english": "Turtwig",
    "japanese": "ナエトル"
  },
  "tympole": {
    "dex_id": 535,
    "english": "Tympole",
    "japanese": "オタマロ"
  },
  "tynamo": {
    "dex_id": 602,
    "english": "Tynamo",
    "japanese": "シビシラス"
  },
  "type null": {
    "dex_id": 772,
    "english": "Type: Null",
    "japanese": "タイプ：ヌル"
  },
  "typenull": {
    "dex_id": 772,
    "english": "Type: Null",
    "japanese": "タイプ：ヌル"
  },
  "typhlosion": {
    "dex_id": 157,
    "english": "Typhlosion",
    "japanese": "バクフーン"
  },
  "tyranitar": {
    "dex_id": 248,
    "english": "Tyranitar",
    "japanese": "バンギラス"
  },
  "tyrantrum": {
    "dex_id": 697,
    "english": "Tyrantrum",
    "japanese": "ガチゴラス"
  },
  "tyrogue": {
    "dex_id": 236,
    "english": "Tyrogue",
    "japanese": "バルキー"
  },
  "tyrunt": {
    "dex_id": 696,
    "english": "Tyrunt",
    "japanese": "チゴラス"
  },
  "umbreon": {
    "dex_id": 197,
    "english": "Umbreon",
    "japanese": "ブラッキー"
  },
  "unfezant": {
    "dex_id": 521,
    "english": "Unfezant",
    "japanese": "ケンホロウ"
  },
  "unown": {
    "dex_id": 201,
    "english": "Unown",
    "japanese": "アンノーン"
  },
  "ursaluna": {
    "dex_id": 901,
    "english": "Ursaluna",
    "japanese": "ガチグマ"
  },
  "ursaring": {
    "dex_id": 217,
    "english": "Ursaring",
    "japanese": "リングマ"
  },
  "urshifu": {
    "dex_id": 892,
    "english": "Urshifu",
    "japanese": "ウーラオス"
  },
  "uxie": {
    "dex_id": 480,
    "english": "Uxie",
    "japanese": "ユクシー"
  },
  "vanillish": {
    "dex_id": 583,
    "english": "Vanillish",
    "japanese": "バニリッチ"
  },
  "vanillite": {
    "dex_id": 582,
    "english": "Vanillite",
    "japanese": "バニプッチ"
  },
  "vanilluxe": {
    "dex_id": 584,
    "english": "Vanilluxe",
    "japanese": "バイバニラ"
  },
  "vaporeon": {
    "dex_id": 134,
    "english": "Vaporeon",
    "japanese": "シャワーズ"
  },
  "varoom": {
    "dex_id": 965,
    "english": "Varoom",
    "japanese": "ブロロン"
  },
  "veluza": {
    "dex_id": 976,
    "english": "Veluza",
    "japanese": "ミガルーサ"
  },
  "venipede": {
    "dex_id": 543,
    "english": "Venipede",
    "japanese": "フシデ"
  },
  "venomoth": {
    "dex_id": 49,
    "english": "Venomoth",
    "japanese": "モルフォン"
  },
  "venonat": {
    "dex_id": 48,
    "english": "Venonat",
    "japanese": "コンパン"
  },
  "venusaur": {
    "dex_id": 3,
    "english": "Venusaur",
    "japanese": "フシギバナ"
  },
  "vespiquen": {
    "dex_id": 416,
    "english": "Vespiquen",
    "japanese": "ビークイン"
  },
  "vibrava": {
    "dex_id": 329,
    "english": "Vibrava",
    "japanese": "ビブラーバ"
  },
  "victini": {
    "dex_id": 494,
    "english": "Victini",
    "japanese": "ビクティニ"
  },
  "victreebel": {
    "dex_id": 71,
    "english": "Victreebel",
    "japanese": "ウツボット"
  },
  "vigoroth": {
    "dex_id": 288,
    "english": "Vigoroth",
    "japanese": "ヤルキモノ"
  },
  "vikavolt": {
    "dex_id": 738,
    "english": "Vikavolt",
    "japanese": "クワガノン"
  },
  "vileplume": {
    "dex_id": 45,
    "english": "Vileplume",
    "japanese": "ラフレシア"
  },
  "virizion": {
    "dex_id": 640,
    "english": "Virizion",
    "japanese": "ビリジオン"
  },
  "vivillon": {
    "dex_id": 666,
    "english": "Vivillon",
    "japanese": "ビビヨン"
  },
  "volbeat": {
    "dex_id": 313,
    "english": "Volbeat",
    "japanese": "バルビート"
  },
  "volcanion": {
    "dex_id": 721,
    "english": "Volcanion",
    "japanese": "ボルケニオン"
  },
  "volcarona": {
    "dex_id": 637,
    "english": "Volcarona",
    "japanese": "ウルガモス"
  },
  "voltorb": {
    "dex_id": 100,
    "english": "Voltorb",
    "japanese": "ビリリダマ"
  },
  "vullaby": {
    "dex_id": 629,
    "english": "Vullaby",
    "japanese": "バルチャイ"
  },
  "vulpix": {
    "dex_id": 37,
    "english": "Vulpix",
    "japanese": "ロコン"
  },
  "wailmer": {
    "dex_id": 320,
    "english": "Wailmer",
    "japanese": "ホエルコ"
  },
  "wailord": {
    "dex_id": 321,
    "english": "Wailord",
    "japanese": "ホエルオー"
  },
  "walking wake": {
    "dex_id": 1009,
    "english": "Walking Wake",
    "japanese": "ウネルミナモ"
  },
  "walkingwake": {
    "dex_id": 1009,
    "english": "Walking Wake",
    "japanese": "ウネルミナモ"
  },
  "walrein": {
    "dex_id": 365,
    "english": "Walrein",
    "japanese": "トドゼルガ"
  },
  "wartortle": {
    "dex_id": 8,
    "english": "Wartortle",
    "japanese": "カメール"
  },
  "watchog": {
    "dex_id": 505,
    "english": "Watchog",
    "japanese": "ミルホッグ"
  },
  "wattrel": {
    "dex_id": 940,
    "english": "Wattrel",
    "japanese": "カイデン"
  },
  "weavile": {
    "dex_id": 461,
    "english": "Weavile",
    "japanese": "マニューラ"
  },
  "weedle": {
    "dex_id": 13,
    "english": "Weedle",
    "japanese": "ビードル"
  },
  "weepinbell": {
    "dex_id": 70,
    "english": "Weepinbell",
    "japanese": "ウツドン"
  },
  "weezing": {
    "dex_id": 110,
    "english": "Weezing",
    "japanese": "マタドガス"
  },
  "whimsicott": {
    "dex_id": 547,
    "english": "Whimsicott",
    "japanese": "エルフーン"
  },
  "whirlipede": {
    "dex_id": 544,
    "english": "Whirlipede",
    "japanese": "ホイーガ"
  },
  "whiscash": {
    "dex_id": 340,
    "english": "Whiscash",
    "japanese": "ナマズン"
  },
  "whismur": {
    "dex_id": 293,
    "english": "Whismur",
    "japanese": "ゴニョニョ"
  },
  "wigglytuff": {
    "dex_id": 40,
    "english": "Wigglytuff",
    "japanese": "プクリン"
  },
  "wiglett": {
    "dex_id": 960,
    "english": "Wiglett",
    "japanese": "ウミディグダ"
  },
  "wimpod": {
    "dex_id": 767,
    "english": "Wimpod",
    "japanese": "コソクムシ"
  },
  "wingull": {
    "dex_id": 278,
    "english": "Wingull",
    "japanese": "キャモメ"
  },
  "wishiwashi": {
    "dex_id": 746,
    "english": "Wishiwashi",
    "japanese": "ヨワシ"
  },
  "wo chien": {
    "dex_id": 1001,
    "english": "Wo-Chien",
    "japanese": "チオンジェン"
  },
  "wobbuffet": {
    "dex_id": 202,
    "english": "Wobbuffet",
    "japanese": "ソーナンス"
  },
  "wochien": {
    "dex_id": 1001,
    "english": "Wo-Chien",
    "japanese": "チオンジェン"
  },
  "woobat": {
    "dex_id": 527,
    "english": "Woobat",
    "japanese": "コロモリ"
  },
  "wooloo": {
    "dex_id": 831,
    "english": "Wooloo",
    "japanese": "ウールー"
  },
  "wooper": {
    "dex_id": 194,
    "english": "Wooper",
    "japanese": "ウパー"
  },
  "wormadam": {
    "dex_id": 413,
    "english": "Wormadam",
    "japanese": "ミノマダム"
  },
  "wugtrio": {
    "dex_id": 961,
    "english": "Wugtrio",
    "japanese": "ウミトリオ"
  },
  "wurmple": {
    "dex_id": 265,
    "english": "Wurmple",
    "japanese": "ケムッソ"
  },
  "wynaut": {
    "dex_id": 360,
    "english": "Wynaut",
    "japanese": "ソーナノ"
  },
  "wyrdeer": {
    "dex_id": 899,
    "english": "Wyrdeer",
    "japanese": "アヤシシ"
  },
  "xatu": {
    "dex_id": 178,
    "english": "Xatu",
    "japanese": "ネイティオ"
  },
  "xerneas": {
    "dex_id": 716,
    "english": "Xerneas",
    "japanese": "ゼルネアス"
  },
  "xurkitree": {
    "dex_id": 796,
    "english": "Xurkitree",
    "japanese": "デンジュモク"
  },
  "yamask": {
    "dex_id": 562,
    "english": "Yamask",
    "japanese": "デスマス"
  },
  "yamper": {
    "dex_id": 835,
    "english": "Yamper",
    "japanese": "ワンパチ"
  },
  "yanma": {
    "dex_id": 193,
    "english": "Yanma",
    "japanese": "ヤンヤンマ"
  },
  "yanmega": {
    "dex_id": 469,
    "english": "Yanmega",
    "japanese": "メガヤンマ"
  },
  "yungoos": {
    "dex_id": 734,
    "english": "Yungoos",
    "japanese": "ヤングース"
  },
  "yveltal": {
    "dex_id": 717,
    "english": "Yveltal",
    "japanese": "イベルタル"
  },
  "zacian": {
    "dex_id": 888,
    "english": "Zacian",
    "japanese": "ザシアン"
  },
  "zamazenta": {
    "dex_id": 889,
    "english": "Zamazenta",
    "japanese": "ザマゼンタ"
  },
  "zangoose": {
    "dex_id": 335,
    "english": "Zangoose",
    "japanese": "ザングース"
  },
  "zapdos": {
    "dex_id": 145,
    "english": "Zapdos",
    "japanese": "サンダー"
  },
  "zarude": {
    "dex_id": 893,
    "english": "Zarude",
    "japanese": "ザルード"
  },
  "zebstrika": {
    "dex_id": 523,
    "english": "Zebstrika",
    "japanese": "ゼブライカ"
  },
  "zekrom": {
    "dex_id": 644,
    "english": "Zekrom",
    "japanese": "ゼクロム"
  },
  "zeraora": {
    "dex_id": 807,
    "english": "Zeraora",
    "japanese": "ゼラオラ"
  },
  "zigzagoon": {
    "dex_id": 263,
    "english": "Zigzagoon",
    "japanese": "ジグザグマ"
  },
  "zoroark": {
    "dex_id": 571,
    "english": "Zoroark",
    "japanese": "ゾロアーク"
  },
  "zorua": {
    "dex_id": 570,
    "english": "Zorua",
    "japanese": "ゾロア"
  },
  "zubat": {
    "dex_id": 41,
    "english": "Zubat",
    "japanese": "ズバット"
  },
  "zweilous": {
    "dex_id": 634,
    "english": "Zweilous",
    "japanese": "ジヘッド"
  },
  "zygarde": {
    "dex_id": 718,
    "english": "Zygarde",
    "japanese": "ジガルデ"
  }
}
