#!/usr/bin/env python3
from __future__ import annotations

import concurrent.futures
import json
import re
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "pokemon_names.py"
SPECIES_LIST_URL = "https://pokeapi.co/api/v2/pokemon-species?limit=2000"
TOKEN_RE = re.compile(r"[a-z0-9]+", re.IGNORECASE)


def main() -> None:
    species_urls = [item["url"] for item in fetch_json(SPECIES_LIST_URL)["results"]]
    entries: list[dict[str, Any]] = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
        for entry in executor.map(fetch_species_entry, species_urls):
            if entry:
                entries.append(entry)

    aliases: dict[str, dict[str, Any]] = {}
    conflicts: set[str] = set()
    for entry in sorted(entries, key=lambda item: item["dex_id"]):
        for alias in build_aliases(entry["english"], entry["slug"]):
            if alias in conflicts:
                continue
            if alias in aliases and aliases[alias]["dex_id"] != entry["dex_id"]:
                aliases.pop(alias, None)
                conflicts.add(alias)
                continue
            aliases[alias] = {
                "dex_id": entry["dex_id"],
                "english": entry["english"],
                "japanese": entry["japanese"],
            }

    write_python_module(aliases)
    print(f"Wrote {len(aliases)} aliases for {len(entries)} Pokemon to {OUTPUT_PATH}")


def fetch_json(url: str) -> dict[str, Any]:
    request = urllib.request.Request(url, headers={"User-Agent": "pricethatpokemon-name-builder/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def fetch_species_entry(url: str) -> dict[str, Any] | None:
    payload = fetch_json(url)
    names = payload.get("names", [])
    english = get_localized_name(names, "en")
    japanese = get_localized_name(names, "ja-Hrkt") or get_localized_name(names, "ja")
    if not english or not japanese:
        return None
    return {
        "dex_id": payload["id"],
        "slug": payload["name"],
        "english": english,
        "japanese": japanese,
    }


def get_localized_name(names: list[dict[str, Any]], language_code: str) -> str | None:
    for name_info in names:
        language = name_info.get("language", {})
        if language.get("name") == language_code and name_info.get("name"):
            return str(name_info["name"])
    return None


def build_aliases(english: str, slug: str) -> set[str]:
    raw_aliases = {
        english,
        slug,
        slug.replace("-", " "),
        slug.replace("-", ""),
    }

    if slug.endswith("-f"):
        base = slug.removesuffix("-f")
        raw_aliases.update({f"{base} female", f"{base} f"})
    if slug.endswith("-m"):
        base = slug.removesuffix("-m")
        raw_aliases.update({f"{base} male", f"{base} m"})

    aliases = {normalize_alias(alias) for alias in raw_aliases}
    return {alias for alias in aliases if alias}


def normalize_alias(value: str) -> str:
    return " ".join(match.group(0).lower() for match in TOKEN_RE.finditer(value))


def write_python_module(aliases: dict[str, dict[str, Any]]) -> None:
    with OUTPUT_PATH.open("w", encoding="utf-8") as output:
        output.write("from __future__ import annotations\n\n")
        output.write("# Generated by scripts/build_pokemon_names.py. Do not edit by hand.\n")
        output.write("POKEMON_NAME_ALIASES = ")
        json.dump(aliases, output, ensure_ascii=False, indent=2, sort_keys=True)
        output.write("\n")


if __name__ == "__main__":
    main()
